---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-pvc
  namespace: vertice-subordinates
  labels:
    app: neo4j
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo

---
apiVersion: v1
kind: Service
metadata:
  name: vertice-neo4j
  namespace: vertice-subordinates
  labels:
    app: neo4j
spec:
  type: ClusterIP
  ports:
    - port: 7474
      targetPort: 7474
      protocol: TCP
      name: http
    - port: 7687
      targetPort: 7687
      protocol: TCP
      name: bolt
  selector:
    app: neo4j

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j
  namespace: vertice-subordinates
  labels:
    app: neo4j
spec:
  serviceName: vertice-neo4j
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
        - name: neo4j
          image: neo4j:5.28-community
          ports:
            - containerPort: 7474
              name: http
            - containerPort: 7687
              name: bolt
          env:
            - name: NEO4J_AUTH
              valueFrom:
                secretKeyRef:
                  name: subordinates-secrets
                  key: NEO4J_USER
            - name: NEO4J_server_memory_heap_initial__size
              value: 512M
            - name: NEO4J_server_memory_heap_max__size
              value: 2G
            - name: NEO4J_server_memory_pagecache_size
              value: 1G
            - name: NEO4J_PLUGINS
              value: '["apoc"]'
          volumeMounts:
            - name: neo4j-storage
              mountPath: /data
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 2
              memory: 4Gi
          livenessProbe:
            httpGet:
              path: /
              port: 7474
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 7474
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
      volumes:
        - name: neo4j-storage
          persistentVolumeClaim:
            claimName: neo4j-pvc

# 🤖 Generated with [Claude Code](https://claude.com/claude-code)
#
# Co-Authored-By: Claude <noreply@anthropic.com>
