global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'service', 'severity']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'constitutional-violations'

receivers:
  - name: 'constitutional-violations'
    webhook_configs:
      - url: 'http://localhost:5001/alerts'
        send_resolved: true
