# Prometheus Configuration for Vértice Constitutional Metrics
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'vertice-dev'
    constitution_version: '3.0'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - 'prometheus-rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'penelope'
    static_configs:
      - targets: ['penelope:8154']
    metrics_path: '/metrics'

  - job_name: 'maba'
    static_configs:
      - targets: ['maba:8152']
    metrics_path: '/metrics'

  - job_name: 'mvp'
    static_configs:
      - targets: ['mvp:8153']
    metrics_path: '/metrics'
