# CVE Whitelist Configuration
#
# This file contains CVEs that have been reviewed and approved for whitelisting.
# All entries MUST have:
# - Valid justification explaining why CVE doesn't apply
# - Expiration date (max 1 year from approval)
# - Owner responsible for re-review
# - Approver (Tech Lead or Security Team)
#
# See DEPENDENCY_POLICY.md for full whitelist process.

version: 1.0.0

whitelisted_cves:
  # ecdsa - Minerva Timing Attack Vulnerability
  - id: CVE-2024-23342
    package: ecdsa==0.19.1
    cvss: 5.9
    severity: MEDIUM
    justification: |
      ecdsa 0.19.1 is vulnerable to Minerva timing attack (side-channel attack). NO FIX AVAILABLE - fundamental Python limitation.

      ATTACK REQUIREMENTS: Requires local access to execution environment, precise timing measurements (hardware access), thousands of samples for statistical analysis. Only affects signature GENERATION (not verification).

      OUR USAGE (LOW RISK): Ethical audit service uses ecdsa ONLY for signature VERIFICATION (read-only) via python-jose for JWT validation. We do NOT generate ECDSA signatures (we use RSA/EdDSA for signing).

      DEPLOYMENT ENVIRONMENT: Containerized deployment (Docker isolation), no local access to container, ephemeral containers, cloud environment with hardware noise (timing attacks ineffective).

      Reference: https://nvd.nist.gov/vuln/detail/CVE-2024-23342

    mitigations:
      - "Signature verification only (no generation)"
      - "Container isolation (no local access)"
      - "Ephemeral containers"
      - "Cloud environment (hardware timing noise)"
      - "Alternative algorithms used for signing (RSA/EdDSA)"

    expires_at: 2026-04-06
    owner: security-team
    approved_by: tech-lead
    approved_at: 2025-10-06
    re_review_date: 2026-01-04
    re_review_status: pending
    re_review_justification: ""

  # ecdsa - Python Side-Channel Limitation (General Advisory)
  - id: PVE-2024-64396
    package: ecdsa==0.19.1
    cvss: 5.9
    severity: MEDIUM
    justification: |
      General advisory that ecdsa does not protect against side-channel attacks. Architectural limitation of Python (no constant-time primitives). Same as CVE-2024-23342. Same mitigations apply.

    mitigations:
      - "Signature verification only (no generation)"
      - "Container isolation"
      - "Alternative algorithms for signing"

    expires_at: 2026-04-06
    owner: security-team
    approved_by: tech-lead
    approved_at: 2025-10-06
    re_review_date: 2026-01-04
    re_review_status: pending
    re_review_justification: ""

  # Example entry (uncomment and modify when needed):
  #
  # - id: CVE-2024-12345
  #   package: example-lib==1.2.3
  #   cvss: 7.5
  #   severity: HIGH
  #   justification: |
  #     This CVE only affects Windows systems via a specific registry key exploit.
  #     Our service runs exclusively on Linux containers with no registry access.
  #
  #     Reference: https://nvd.nist.gov/vuln/detail/CVE-2024-12345
  #     Analysis: Confirmed with Security Team on 2025-01-15
  #
  #   mitigations:
  #     - "Containerized deployment (no host access)"
  #     - "Network segmentation (isolated subnet)"
  #     - "SELinux enforcing mode"
  #
  #   expires_at: 2025-12-31
  #   owner: security-team
  #   approved_by: tech-lead-name
  #   approved_at: 2025-01-15
  #
  #   re_review_date: 2025-10-01
  #   re_review_status: pending  # pending | approved | rejected
  #   re_review_justification: ""

# Validation Rules (enforced by check-cve-whitelist.sh):
# ✅ All fields are required
# ✅ expires_at must be <= 1 year from approved_at
# ✅ re_review_date must be every 90 days
# ✅ CVSS score must match official NVD database
# ✅ Package version must match exactly (no ranges)
# ✅ Justification must be >= 50 characters
