// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: maximus/maximus.proto

package maximus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DecisionEvent_EventType int32

const (
	DecisionEvent_EVENT_TYPE_UNSPECIFIED DecisionEvent_EventType = 0
	DecisionEvent_NEW_DECISION           DecisionEvent_EventType = 1
	DecisionEvent_DECISION_UPDATED       DecisionEvent_EventType = 2
	DecisionEvent_DECISION_RESOLVED      DecisionEvent_EventType = 3
	DecisionEvent_DECISION_APPROVED      DecisionEvent_EventType = 4
	DecisionEvent_DECISION_REJECTED      DecisionEvent_EventType = 5
	DecisionEvent_DECISION_CANCELLED     DecisionEvent_EventType = 6
)

// Enum value maps for DecisionEvent_EventType.
var (
	DecisionEvent_EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "NEW_DECISION",
		2: "DECISION_UPDATED",
		3: "DECISION_RESOLVED",
		4: "DECISION_APPROVED",
		5: "DECISION_REJECTED",
		6: "DECISION_CANCELLED",
	}
	DecisionEvent_EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"NEW_DECISION":           1,
		"DECISION_UPDATED":       2,
		"DECISION_RESOLVED":      3,
		"DECISION_APPROVED":      4,
		"DECISION_REJECTED":      5,
		"DECISION_CANCELLED":     6,
	}
)

func (x DecisionEvent_EventType) Enum() *DecisionEvent_EventType {
	p := new(DecisionEvent_EventType)
	*p = x
	return p
}

func (x DecisionEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DecisionEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_maximus_maximus_proto_enumTypes[0].Descriptor()
}

func (DecisionEvent_EventType) Type() protoreflect.EnumType {
	return &file_maximus_maximus_proto_enumTypes[0]
}

func (x DecisionEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DecisionEvent_EventType.Descriptor instead.
func (DecisionEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_maximus_maximus_proto_rawDescGZIP(), []int{11, 0}
}

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN         HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING         HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING     HealthCheckResponse_ServingStatus = 2
	HealthCheckResponse_SERVICE_UNKNOWN HealthCheckResponse_ServingStatus = 3
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
		3: "SERVICE_UNKNOWN",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":         0,
		"SERVING":         1,
		"NOT_SERVING":     2,
		"SERVICE_UNKNOWN": 3,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_maximus_maximus_proto_enumTypes[1].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_maximus_maximus_proto_enumTypes[1]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_maximus_maximus_proto_rawDescGZIP(), []int{15, 0}
}

type SubmitDecisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DecisionType  string                 `protobuf:"bytes,1,opt,name=decision_type,json=decisionType,proto3" json:"decision_type,omitempty"` // e.g., "deployment", "scaling", "security"
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Context       string                 `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`   // e.g., "production", "staging"
	Metadata      *structpb.Struct       `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"` // Flexible metadata
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Priority      string                 `protobuf:"bytes,7,opt,name=priority,proto3" json:"priority,omitempty"`                          // "low", "medium", "high", "critical"
	RequesterId   string                 `protobuf:"bytes,8,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"` // User/service requesting decision
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitDecisionRequest) Reset() {
	*x = SubmitDecisionRequest{}
	mi := &file_maximus_maximus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitDecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitDecisionRequest) ProtoMessage() {}

func (x *SubmitDecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_maximus_maximus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitDecisionRequest.ProtoReflect.Descriptor instead.
func (*SubmitDecisionRequest) Descriptor() ([]byte, []int) {
	return file_maximus_maximus_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitDecisionRequest) GetDecisionType() string {
	if x != nil {
		return x.DecisionType
	}
	return ""
}

func (x *SubmitDecisionRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SubmitDecisionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SubmitDecisionRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *SubmitDecisionRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SubmitDecisionRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SubmitDecisionRequest) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *SubmitDecisionRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

type SubmitDecisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DecisionId    string                 `protobuf:"bytes,1,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "pending", "approved", "rejected"
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitDecisionResponse) Reset() {
	*x = SubmitDecisionResponse{}
	mi := &file_maximus_maximus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitDecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitDecisionResponse) ProtoMessage() {}

func (x *SubmitDecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_maximus_maximus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitDecisionResponse.ProtoReflect.Descriptor instead.
func (*SubmitDecisionResponse) Descriptor() ([]byte, []int) {
	return file_maximus_maximus_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitDecisionResponse) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *SubmitDecisionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubmitDecisionResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SubmitDecisionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetDecisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DecisionId    string                 `protobuf:"bytes,1,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDecisionRequest) Reset() {
	*x = GetDecisionRequest{}
	mi := &file_maximus_maximus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDecisionRequest) ProtoMessage() {}

func (x *GetDecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_maximus_maximus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDecisionRequest.ProtoReflect.Descriptor instead.
func (*GetDecisionRequest) Descriptor() ([]byte, []int) {
	return file_maximus_maximus_proto_rawDescGZIP(), []int{2}
}

func (x *GetDecisionRequest) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

type ListDecisionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filters
	Status       string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                                 // Filter by status
	DecisionType string   `protobuf:"bytes,2,opt,name=decision_type,json=decisionType,proto3" json:"decision_type,omitempty"` // Filter by type
	Context      string   `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`                               // Filter by context
	Tags         []string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`                                     // Filter by tags
	// Pagination
	Page     int32 `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32 `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Sorting
	SortBy    string `protobuf:"bytes,7,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`          // "created_at", "priority", "status"
	SortOrder string `protobuf:"bytes,8,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"` // "asc" or "desc"
	// Time range
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDecisionsRequest) Reset() {
	*x = ListDecisionsRequest{}
	mi := &file_maximus_maximus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDecisionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDecisionsRequest) ProtoMessage() {}

func (x *ListDecisionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_maximus_maximus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDecisionsRequest.ProtoReflect.Descriptor instead.
func (*ListDecisionsRequest) Descriptor() ([]byte, []int) {
	return file_maximus_maximus_proto_rawDescGZIP(), []int{3}
}

func (x *ListDecisionsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListDecisionsRequest) GetDecisionType() string {
	if x != nil {
		return x.DecisionType
	}
	return ""
}

func (x *ListDecisionsRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *ListDecisionsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ListDecisionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDecisionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDecisionsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListDecisionsRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

func (x *ListDecisionsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ListDecisionsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type ListDecisionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decisions     []*Decision            `protobuf:"bytes,1,rep,name=decisions,proto3" json:"decisions,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	HasMore       bool                   `protobuf:"varint,5,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDecisionsResponse) Reset() {
	*x = ListDecisionsResponse{}
	mi := &file_maximus_maximus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDecisionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDecisionsResponse) ProtoMessage() {}

func (x *ListDecisionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_maximus_maximus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDecisionsResponse.ProtoReflect.Descriptor instead.
func (*ListDecisionsResponse) Descriptor() ([]byte, []int) {
	return file_maximus_maximus_proto_rawDescGZIP(), []int{4}
}

func (x *ListDecisionsResponse) GetDecisions() []*Decision {
	if x != nil {
		return x.Decisions
	}
	return nil
}

func (x *ListDecisionsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListDecisionsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDecisionsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDecisionsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type UpdateDecisionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DecisionId    string                 `protobuf:"bytes,1,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	NewStatus     string                 `protobuf:"bytes,2,opt,name=new_status,json=newStatus,proto3" json:"new_status,omitempty"` // "approved", "rejected", "in_review"
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,4,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDecisionStatusRequest) Reset() {
	*x = UpdateDecisionStatusRequest{}
	mi := &file_maximus_maximus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDecisionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDecisionStatusRequest) ProtoMessage() {}

func (x *UpdateDecisionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_maximus_maximus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDecisionStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateDecisionStatusRequest) Descriptor() ([]byte, []int) {
	return file_maximus_maximus_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateDecisionStatusRequest) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *UpdateDecisionStatusRequest) GetNewStatus() string {
	if x != nil {
		return x.NewStatus
	}
	return ""
}

func (x *UpdateDecisionStatusRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *UpdateDecisionStatusRequest) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type DeleteDecisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DecisionId    string                 `protobuf:"bytes,1,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDecisionRequest) Reset() {
	*x = DeleteDecisionRequest{}
	mi := &file_maximus_maximus_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDecisionRequest) ProtoMessage() {}

func (x *DeleteDecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_maximus_maximus_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDecisionRequest.ProtoReflect.Descriptor instead.
func (*DeleteDecisionRequest) Descriptor() ([]byte, []int) {
	return file_maximus_maximus_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteDecisionRequest) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *DeleteDecisionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeleteDecisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDecisionResponse) Reset() {
	*x = DeleteDecisionResponse{}
	mi := &file_maximus_maximus_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDecisionResponse) ProtoMessage() {}

func (x *DeleteDecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_maximus_maximus_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDecisionResponse.ProtoReflect.Descriptor instead.
func (*DeleteDecisionResponse) Descriptor() ([]byte, []int) {
	return file_maximus_maximus_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteDecisionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteDecisionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Decision struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	DecisionId   string                 `protobuf:"bytes,1,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	DecisionType string                 `protobuf:"bytes,2,opt,name=decision_type,json=decisionType,proto3" json:"decision_type,omitempty"`
	Title        string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description  string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Context      string                 `protobuf:"bytes,5,opt,name=context,proto3" json:"context,omitempty"`
	Status       string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Priority     string                 `protobuf:"bytes,7,opt,name=priority,proto3" json:"priority,omitempty"`
	Tags         []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata     *structpb.Struct       `protobuf:"bytes,9,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Timestamps
	CreatedAt  *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt  *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ResolvedAt *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=resolved_at,json=resolvedAt,proto3" json:"resolved_at,omitempty"`
	// Tracking
	RequesterId      string `protobuf:"bytes,13,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	ApproverId       string `protobuf:"bytes,14,opt,name=approver_id,json=approverId,proto3" json:"approver_id,omitempty"`
	ResolutionReason string `protobuf:"bytes,15,opt,name=resolution_reason,json=resolutionReason,proto3" json:"resolution_reason,omitempty"`
	// Metrics
	ProcessingTimeMs int64 `protobuf:"varint,16,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	RevisionCount    int32 `protobuf:"varint,17,opt,name=revision_count,json=revisionCount,proto3" json:"revision_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Decision) Reset() {
	*x = Decision{}
	mi := &file_maximus_maximus_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decision) ProtoMessage() {}

func (x *Decision) ProtoReflect() protoreflect.Message {
	mi := &file_maximus_maximus_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decision.ProtoReflect.Descriptor instead.
func (*Decision) Descriptor() ([]byte, []int) {
	return file_maximus_maximus_proto_rawDescGZIP(), []int{8}
}

func (x *Decision) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *Decision) GetDecisionType() string {
	if x != nil {
		return x.DecisionType
	}
	return ""
}

func (x *Decision) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Decision) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Decision) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *Decision) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Decision) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *Decision) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Decision) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Decision) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Decision) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Decision) GetResolvedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ResolvedAt
	}
	return nil
}

func (x *Decision) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *Decision) GetApproverId() string {
	if x != nil {
		return x.ApproverId
	}
	return ""
}

func (x *Decision) GetResolutionReason() string {
	if x != nil {
		return x.ResolutionReason
	}
	return ""
}

func (x *Decision) GetProcessingTimeMs() int64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

func (x *Decision) GetRevisionCount() int32 {
	if x != nil {
		return x.RevisionCount
	}
	return 0
}

type WatchDecisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DecisionId    string                 `protobuf:"bytes,1,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchDecisionRequest) Reset() {
	*x = WatchDecisionRequest{}
	mi := &file_maximus_maximus_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchDecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchDecisionRequest) ProtoMessage() {}

func (x *WatchDecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_maximus_maximus_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchDecisionRequest.ProtoReflect.Descriptor instead.
func (*WatchDecisionRequest) Descriptor() ([]byte, []int) {
	return file_maximus_maximus_proto_rawDescGZIP(), []int{9}
}

func (x *WatchDecisionRequest) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

type StreamEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filters for event stream
	DecisionTypes []string `protobuf:"bytes,1,rep,name=decision_types,json=decisionTypes,proto3" json:"decision_types,omitempty"`
	Statuses      []string `protobuf:"bytes,2,rep,name=statuses,proto3" json:"statuses,omitempty"`
	Context       string   `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_maximus_maximus_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_maximus_maximus_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_maximus_maximus_proto_rawDescGZIP(), []int{10}
}

func (x *StreamEventsRequest) GetDecisionTypes() []string {
	if x != nil {
		return x.DecisionTypes
	}
	return nil
}

func (x *StreamEventsRequest) GetStatuses() []string {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *StreamEventsRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

type DecisionEvent struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	EventType     DecisionEvent_EventType `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=maximus.v1.DecisionEvent_EventType" json:"event_type,omitempty"`
	DecisionId    string                  `protobuf:"bytes,2,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	Decision      *Decision               `protobuf:"bytes,3,opt,name=decision,proto3" json:"decision,omitempty"`
	Timestamp     *timestamppb.Timestamp  `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TriggeredBy   string                  `protobuf:"bytes,5,opt,name=triggered_by,json=triggeredBy,proto3" json:"triggered_by,omitempty"`
	Changes       *structpb.Struct        `protobuf:"bytes,6,opt,name=changes,proto3" json:"changes,omitempty"` // What changed (for UPDATED events)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionEvent) Reset() {
	*x = DecisionEvent{}
	mi := &file_maximus_maximus_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionEvent) ProtoMessage() {}

func (x *DecisionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_maximus_maximus_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionEvent.ProtoReflect.Descriptor instead.
func (*DecisionEvent) Descriptor() ([]byte, []int) {
	return file_maximus_maximus_proto_rawDescGZIP(), []int{11}
}

func (x *DecisionEvent) GetEventType() DecisionEvent_EventType {
	if x != nil {
		return x.EventType
	}
	return DecisionEvent_EVENT_TYPE_UNSPECIFIED
}

func (x *DecisionEvent) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *DecisionEvent) GetDecision() *Decision {
	if x != nil {
		return x.Decision
	}
	return nil
}

func (x *DecisionEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DecisionEvent) GetTriggeredBy() string {
	if x != nil {
		return x.TriggeredBy
	}
	return ""
}

func (x *DecisionEvent) GetChanges() *structpb.Struct {
	if x != nil {
		return x.Changes
	}
	return nil
}

type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Context       string                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`                                  // Filter by context
	DecisionTypes []string               `protobuf:"bytes,4,rep,name=decision_types,json=decisionTypes,proto3" json:"decision_types,omitempty"` // Filter by types
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_maximus_maximus_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_maximus_maximus_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_maximus_maximus_proto_rawDescGZIP(), []int{12}
}

func (x *GetMetricsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetMetricsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GetMetricsRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *GetMetricsRequest) GetDecisionTypes() []string {
	if x != nil {
		return x.DecisionTypes
	}
	return nil
}

type GovernanceMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Counts
	TotalDecisions    int64 `protobuf:"varint,1,opt,name=total_decisions,json=totalDecisions,proto3" json:"total_decisions,omitempty"`
	PendingDecisions  int64 `protobuf:"varint,2,opt,name=pending_decisions,json=pendingDecisions,proto3" json:"pending_decisions,omitempty"`
	ApprovedDecisions int64 `protobuf:"varint,3,opt,name=approved_decisions,json=approvedDecisions,proto3" json:"approved_decisions,omitempty"`
	RejectedDecisions int64 `protobuf:"varint,4,opt,name=rejected_decisions,json=rejectedDecisions,proto3" json:"rejected_decisions,omitempty"`
	// Performance
	AvgResolutionTimeMs float64 `protobuf:"fixed64,5,opt,name=avg_resolution_time_ms,json=avgResolutionTimeMs,proto3" json:"avg_resolution_time_ms,omitempty"`
	P50ResolutionTimeMs float64 `protobuf:"fixed64,6,opt,name=p50_resolution_time_ms,json=p50ResolutionTimeMs,proto3" json:"p50_resolution_time_ms,omitempty"`
	P95ResolutionTimeMs float64 `protobuf:"fixed64,7,opt,name=p95_resolution_time_ms,json=p95ResolutionTimeMs,proto3" json:"p95_resolution_time_ms,omitempty"`
	P99ResolutionTimeMs float64 `protobuf:"fixed64,8,opt,name=p99_resolution_time_ms,json=p99ResolutionTimeMs,proto3" json:"p99_resolution_time_ms,omitempty"`
	// By priority
	DecisionsByPriority map[string]int64 `protobuf:"bytes,9,rep,name=decisions_by_priority,json=decisionsByPriority,proto3" json:"decisions_by_priority,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// By type
	DecisionsByType map[string]int64 `protobuf:"bytes,10,rep,name=decisions_by_type,json=decisionsByType,proto3" json:"decisions_by_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Time range
	StartTime *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Approval rate
	ApprovalRate  float64 `protobuf:"fixed64,13,opt,name=approval_rate,json=approvalRate,proto3" json:"approval_rate,omitempty"` // Percentage of approved decisions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GovernanceMetrics) Reset() {
	*x = GovernanceMetrics{}
	mi := &file_maximus_maximus_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GovernanceMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GovernanceMetrics) ProtoMessage() {}

func (x *GovernanceMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_maximus_maximus_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GovernanceMetrics.ProtoReflect.Descriptor instead.
func (*GovernanceMetrics) Descriptor() ([]byte, []int) {
	return file_maximus_maximus_proto_rawDescGZIP(), []int{13}
}

func (x *GovernanceMetrics) GetTotalDecisions() int64 {
	if x != nil {
		return x.TotalDecisions
	}
	return 0
}

func (x *GovernanceMetrics) GetPendingDecisions() int64 {
	if x != nil {
		return x.PendingDecisions
	}
	return 0
}

func (x *GovernanceMetrics) GetApprovedDecisions() int64 {
	if x != nil {
		return x.ApprovedDecisions
	}
	return 0
}

func (x *GovernanceMetrics) GetRejectedDecisions() int64 {
	if x != nil {
		return x.RejectedDecisions
	}
	return 0
}

func (x *GovernanceMetrics) GetAvgResolutionTimeMs() float64 {
	if x != nil {
		return x.AvgResolutionTimeMs
	}
	return 0
}

func (x *GovernanceMetrics) GetP50ResolutionTimeMs() float64 {
	if x != nil {
		return x.P50ResolutionTimeMs
	}
	return 0
}

func (x *GovernanceMetrics) GetP95ResolutionTimeMs() float64 {
	if x != nil {
		return x.P95ResolutionTimeMs
	}
	return 0
}

func (x *GovernanceMetrics) GetP99ResolutionTimeMs() float64 {
	if x != nil {
		return x.P99ResolutionTimeMs
	}
	return 0
}

func (x *GovernanceMetrics) GetDecisionsByPriority() map[string]int64 {
	if x != nil {
		return x.DecisionsByPriority
	}
	return nil
}

func (x *GovernanceMetrics) GetDecisionsByType() map[string]int64 {
	if x != nil {
		return x.DecisionsByType
	}
	return nil
}

func (x *GovernanceMetrics) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GovernanceMetrics) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GovernanceMetrics) GetApprovalRate() float64 {
	if x != nil {
		return x.ApprovalRate
	}
	return 0
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"` // Optional: check specific sub-service
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_maximus_maximus_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_maximus_maximus_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_maximus_maximus_proto_rawDescGZIP(), []int{14}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthCheckResponse struct {
	state     protoimpl.MessageState            `protogen:"open.v1"`
	Status    HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=maximus.v1.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	Version   string                            `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp *timestamppb.Timestamp            `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Detailed health
	Components          map[string]bool `protobuf:"bytes,4,rep,name=components,proto3" json:"components,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // e.g., {"database": true, "kafka": true}
	UnhealthyComponents []string        `protobuf:"bytes,5,rep,name=unhealthy_components,json=unhealthyComponents,proto3" json:"unhealthy_components,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_maximus_maximus_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_maximus_maximus_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_maximus_maximus_proto_rawDescGZIP(), []int{15}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HealthCheckResponse) GetComponents() map[string]bool {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *HealthCheckResponse) GetUnhealthyComponents() []string {
	if x != nil {
		return x.UnhealthyComponents
	}
	return nil
}

type BatchSubmitRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Decisions     []*SubmitDecisionRequest `protobuf:"bytes,1,rep,name=decisions,proto3" json:"decisions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSubmitRequest) Reset() {
	*x = BatchSubmitRequest{}
	mi := &file_maximus_maximus_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSubmitRequest) ProtoMessage() {}

func (x *BatchSubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_maximus_maximus_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSubmitRequest.ProtoReflect.Descriptor instead.
func (*BatchSubmitRequest) Descriptor() ([]byte, []int) {
	return file_maximus_maximus_proto_rawDescGZIP(), []int{16}
}

func (x *BatchSubmitRequest) GetDecisions() []*SubmitDecisionRequest {
	if x != nil {
		return x.Decisions
	}
	return nil
}

type BatchSubmitResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Results       []*BatchSubmitResponse_Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	TotalCount    int32                         `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	SuccessCount  int32                         `protobuf:"varint,3,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailureCount  int32                         `protobuf:"varint,4,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSubmitResponse) Reset() {
	*x = BatchSubmitResponse{}
	mi := &file_maximus_maximus_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSubmitResponse) ProtoMessage() {}

func (x *BatchSubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_maximus_maximus_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSubmitResponse.ProtoReflect.Descriptor instead.
func (*BatchSubmitResponse) Descriptor() ([]byte, []int) {
	return file_maximus_maximus_proto_rawDescGZIP(), []int{17}
}

func (x *BatchSubmitResponse) GetResults() []*BatchSubmitResponse_Result {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *BatchSubmitResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *BatchSubmitResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BatchSubmitResponse) GetFailureCount() int32 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

type BatchSubmitResponse_Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"` // Index in original batch
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	DecisionId    string                 `protobuf:"bytes,3,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"` // If success
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`                             // If failure
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSubmitResponse_Result) Reset() {
	*x = BatchSubmitResponse_Result{}
	mi := &file_maximus_maximus_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSubmitResponse_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSubmitResponse_Result) ProtoMessage() {}

func (x *BatchSubmitResponse_Result) ProtoReflect() protoreflect.Message {
	mi := &file_maximus_maximus_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSubmitResponse_Result.ProtoReflect.Descriptor instead.
func (*BatchSubmitResponse_Result) Descriptor() ([]byte, []int) {
	return file_maximus_maximus_proto_rawDescGZIP(), []int{17, 0}
}

func (x *BatchSubmitResponse_Result) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *BatchSubmitResponse_Result) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BatchSubmitResponse_Result) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *BatchSubmitResponse_Result) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_maximus_maximus_proto protoreflect.FileDescriptor

const file_maximus_maximus_proto_rawDesc = "" +
	"\n" +
	"\x15maximus/maximus.proto\x12\n" +
	"maximus.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x96\x02\n" +
	"\x15SubmitDecisionRequest\x12#\n" +
	"\rdecision_type\x18\x01 \x01(\tR\fdecisionType\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\acontext\x18\x04 \x01(\tR\acontext\x123\n" +
	"\bmetadata\x18\x05 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x1a\n" +
	"\bpriority\x18\a \x01(\tR\bpriority\x12!\n" +
	"\frequester_id\x18\b \x01(\tR\vrequesterId\"\xa6\x01\n" +
	"\x16SubmitDecisionResponse\x12\x1f\n" +
	"\vdecision_id\x18\x01 \x01(\tR\n" +
	"decisionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"5\n" +
	"\x12GetDecisionRequest\x12\x1f\n" +
	"\vdecision_id\x18\x01 \x01(\tR\n" +
	"decisionId\"\xdc\x02\n" +
	"\x14ListDecisionsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12#\n" +
	"\rdecision_type\x18\x02 \x01(\tR\fdecisionType\x12\x18\n" +
	"\acontext\x18\x03 \x01(\tR\acontext\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\x12\x17\n" +
	"\asort_by\x18\a \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\b \x01(\tR\tsortOrder\x129\n" +
	"\n" +
	"start_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\xb8\x01\n" +
	"\x15ListDecisionsResponse\x122\n" +
	"\tdecisions\x18\x01 \x03(\v2\x14.maximus.v1.DecisionR\tdecisions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x19\n" +
	"\bhas_more\x18\x05 \x01(\bR\ahasMore\"\x94\x01\n" +
	"\x1bUpdateDecisionStatusRequest\x12\x1f\n" +
	"\vdecision_id\x18\x01 \x01(\tR\n" +
	"decisionId\x12\x1d\n" +
	"\n" +
	"new_status\x18\x02 \x01(\tR\tnewStatus\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x04 \x01(\tR\tupdatedBy\"P\n" +
	"\x15DeleteDecisionRequest\x12\x1f\n" +
	"\vdecision_id\x18\x01 \x01(\tR\n" +
	"decisionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"L\n" +
	"\x16DeleteDecisionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x98\x05\n" +
	"\bDecision\x12\x1f\n" +
	"\vdecision_id\x18\x01 \x01(\tR\n" +
	"decisionId\x12#\n" +
	"\rdecision_type\x18\x02 \x01(\tR\fdecisionType\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\acontext\x18\x05 \x01(\tR\acontext\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1a\n" +
	"\bpriority\x18\a \x01(\tR\bpriority\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x123\n" +
	"\bmetadata\x18\t \x01(\v2\x17.google.protobuf.StructR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12;\n" +
	"\vresolved_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"resolvedAt\x12!\n" +
	"\frequester_id\x18\r \x01(\tR\vrequesterId\x12\x1f\n" +
	"\vapprover_id\x18\x0e \x01(\tR\n" +
	"approverId\x12+\n" +
	"\x11resolution_reason\x18\x0f \x01(\tR\x10resolutionReason\x12,\n" +
	"\x12processing_time_ms\x18\x10 \x01(\x03R\x10processingTimeMs\x12%\n" +
	"\x0erevision_count\x18\x11 \x01(\x05R\rrevisionCount\"7\n" +
	"\x14WatchDecisionRequest\x12\x1f\n" +
	"\vdecision_id\x18\x01 \x01(\tR\n" +
	"decisionId\"r\n" +
	"\x13StreamEventsRequest\x12%\n" +
	"\x0edecision_types\x18\x01 \x03(\tR\rdecisionTypes\x12\x1a\n" +
	"\bstatuses\x18\x02 \x03(\tR\bstatuses\x12\x18\n" +
	"\acontext\x18\x03 \x01(\tR\acontext\"\xe5\x03\n" +
	"\rDecisionEvent\x12B\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2#.maximus.v1.DecisionEvent.EventTypeR\teventType\x12\x1f\n" +
	"\vdecision_id\x18\x02 \x01(\tR\n" +
	"decisionId\x120\n" +
	"\bdecision\x18\x03 \x01(\v2\x14.maximus.v1.DecisionR\bdecision\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12!\n" +
	"\ftriggered_by\x18\x05 \x01(\tR\vtriggeredBy\x121\n" +
	"\achanges\x18\x06 \x01(\v2\x17.google.protobuf.StructR\achanges\"\xac\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fNEW_DECISION\x10\x01\x12\x14\n" +
	"\x10DECISION_UPDATED\x10\x02\x12\x15\n" +
	"\x11DECISION_RESOLVED\x10\x03\x12\x15\n" +
	"\x11DECISION_APPROVED\x10\x04\x12\x15\n" +
	"\x11DECISION_REJECTED\x10\x05\x12\x16\n" +
	"\x12DECISION_CANCELLED\x10\x06\"\xc6\x01\n" +
	"\x11GetMetricsRequest\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x18\n" +
	"\acontext\x18\x03 \x01(\tR\acontext\x12%\n" +
	"\x0edecision_types\x18\x04 \x03(\tR\rdecisionTypes\"\x8a\a\n" +
	"\x11GovernanceMetrics\x12'\n" +
	"\x0ftotal_decisions\x18\x01 \x01(\x03R\x0etotalDecisions\x12+\n" +
	"\x11pending_decisions\x18\x02 \x01(\x03R\x10pendingDecisions\x12-\n" +
	"\x12approved_decisions\x18\x03 \x01(\x03R\x11approvedDecisions\x12-\n" +
	"\x12rejected_decisions\x18\x04 \x01(\x03R\x11rejectedDecisions\x123\n" +
	"\x16avg_resolution_time_ms\x18\x05 \x01(\x01R\x13avgResolutionTimeMs\x123\n" +
	"\x16p50_resolution_time_ms\x18\x06 \x01(\x01R\x13p50ResolutionTimeMs\x123\n" +
	"\x16p95_resolution_time_ms\x18\a \x01(\x01R\x13p95ResolutionTimeMs\x123\n" +
	"\x16p99_resolution_time_ms\x18\b \x01(\x01R\x13p99ResolutionTimeMs\x12j\n" +
	"\x15decisions_by_priority\x18\t \x03(\v26.maximus.v1.GovernanceMetrics.DecisionsByPriorityEntryR\x13decisionsByPriority\x12^\n" +
	"\x11decisions_by_type\x18\n" +
	" \x03(\v22.maximus.v1.GovernanceMetrics.DecisionsByTypeEntryR\x0fdecisionsByType\x129\n" +
	"\n" +
	"start_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12#\n" +
	"\rapproval_rate\x18\r \x01(\x01R\fapprovalRate\x1aF\n" +
	"\x18DecisionsByPriorityEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aB\n" +
	"\x14DecisionsByTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xc4\x03\n" +
	"\x13HealthCheckResponse\x12E\n" +
	"\x06status\x18\x01 \x01(\x0e2-.maximus.v1.HealthCheckResponse.ServingStatusR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12O\n" +
	"\n" +
	"components\x18\x04 \x03(\v2/.maximus.v1.HealthCheckResponse.ComponentsEntryR\n" +
	"components\x121\n" +
	"\x14unhealthy_components\x18\x05 \x03(\tR\x13unhealthyComponents\x1a=\n" +
	"\x0fComponentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"O\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\x12\x13\n" +
	"\x0fSERVICE_UNKNOWN\x10\x03\"U\n" +
	"\x12BatchSubmitRequest\x12?\n" +
	"\tdecisions\x18\x01 \x03(\v2!.maximus.v1.SubmitDecisionRequestR\tdecisions\"\xb3\x02\n" +
	"\x13BatchSubmitResponse\x12@\n" +
	"\aresults\x18\x01 \x03(\v2&.maximus.v1.BatchSubmitResponse.ResultR\aresults\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12#\n" +
	"\rsuccess_count\x18\x03 \x01(\x05R\fsuccessCount\x12#\n" +
	"\rfailure_count\x18\x04 \x01(\x05R\ffailureCount\x1ao\n" +
	"\x06Result\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1f\n" +
	"\vdecision_id\x18\x03 \x01(\tR\n" +
	"decisionId\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error2\xde\x06\n" +
	"\x13MaximusOrchestrator\x12W\n" +
	"\x0eSubmitDecision\x12!.maximus.v1.SubmitDecisionRequest\x1a\".maximus.v1.SubmitDecisionResponse\x12C\n" +
	"\vGetDecision\x12\x1e.maximus.v1.GetDecisionRequest\x1a\x14.maximus.v1.Decision\x12T\n" +
	"\rListDecisions\x12 .maximus.v1.ListDecisionsRequest\x1a!.maximus.v1.ListDecisionsResponse\x12U\n" +
	"\x14UpdateDecisionStatus\x12'.maximus.v1.UpdateDecisionStatusRequest\x1a\x14.maximus.v1.Decision\x12W\n" +
	"\x0eDeleteDecision\x12!.maximus.v1.DeleteDecisionRequest\x1a\".maximus.v1.DeleteDecisionResponse\x12N\n" +
	"\rWatchDecision\x12 .maximus.v1.WatchDecisionRequest\x1a\x19.maximus.v1.DecisionEvent0\x01\x12O\n" +
	"\x0fStreamAllEvents\x12\x1f.maximus.v1.StreamEventsRequest\x1a\x19.maximus.v1.DecisionEvent0\x01\x12T\n" +
	"\x14GetGovernanceMetrics\x12\x1d.maximus.v1.GetMetricsRequest\x1a\x1d.maximus.v1.GovernanceMetrics\x12S\n" +
	"\x10GetServiceHealth\x12\x1e.maximus.v1.HealthCheckRequest\x1a\x1f.maximus.v1.HealthCheckResponse\x12W\n" +
	"\x14BatchSubmitDecisions\x12\x1e.maximus.v1.BatchSubmitRequest\x1a\x1f.maximus.v1.BatchSubmitResponseB-Z+github.com/vertice/vcli-go/api/grpc/maximusb\x06proto3"

var (
	file_maximus_maximus_proto_rawDescOnce sync.Once
	file_maximus_maximus_proto_rawDescData []byte
)

func file_maximus_maximus_proto_rawDescGZIP() []byte {
	file_maximus_maximus_proto_rawDescOnce.Do(func() {
		file_maximus_maximus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_maximus_maximus_proto_rawDesc), len(file_maximus_maximus_proto_rawDesc)))
	})
	return file_maximus_maximus_proto_rawDescData
}

var file_maximus_maximus_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_maximus_maximus_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_maximus_maximus_proto_goTypes = []any{
	(DecisionEvent_EventType)(0),           // 0: maximus.v1.DecisionEvent.EventType
	(HealthCheckResponse_ServingStatus)(0), // 1: maximus.v1.HealthCheckResponse.ServingStatus
	(*SubmitDecisionRequest)(nil),          // 2: maximus.v1.SubmitDecisionRequest
	(*SubmitDecisionResponse)(nil),         // 3: maximus.v1.SubmitDecisionResponse
	(*GetDecisionRequest)(nil),             // 4: maximus.v1.GetDecisionRequest
	(*ListDecisionsRequest)(nil),           // 5: maximus.v1.ListDecisionsRequest
	(*ListDecisionsResponse)(nil),          // 6: maximus.v1.ListDecisionsResponse
	(*UpdateDecisionStatusRequest)(nil),    // 7: maximus.v1.UpdateDecisionStatusRequest
	(*DeleteDecisionRequest)(nil),          // 8: maximus.v1.DeleteDecisionRequest
	(*DeleteDecisionResponse)(nil),         // 9: maximus.v1.DeleteDecisionResponse
	(*Decision)(nil),                       // 10: maximus.v1.Decision
	(*WatchDecisionRequest)(nil),           // 11: maximus.v1.WatchDecisionRequest
	(*StreamEventsRequest)(nil),            // 12: maximus.v1.StreamEventsRequest
	(*DecisionEvent)(nil),                  // 13: maximus.v1.DecisionEvent
	(*GetMetricsRequest)(nil),              // 14: maximus.v1.GetMetricsRequest
	(*GovernanceMetrics)(nil),              // 15: maximus.v1.GovernanceMetrics
	(*HealthCheckRequest)(nil),             // 16: maximus.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 17: maximus.v1.HealthCheckResponse
	(*BatchSubmitRequest)(nil),             // 18: maximus.v1.BatchSubmitRequest
	(*BatchSubmitResponse)(nil),            // 19: maximus.v1.BatchSubmitResponse
	nil,                                    // 20: maximus.v1.GovernanceMetrics.DecisionsByPriorityEntry
	nil,                                    // 21: maximus.v1.GovernanceMetrics.DecisionsByTypeEntry
	nil,                                    // 22: maximus.v1.HealthCheckResponse.ComponentsEntry
	(*BatchSubmitResponse_Result)(nil),     // 23: maximus.v1.BatchSubmitResponse.Result
	(*structpb.Struct)(nil),                // 24: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),          // 25: google.protobuf.Timestamp
}
var file_maximus_maximus_proto_depIdxs = []int32{
	24, // 0: maximus.v1.SubmitDecisionRequest.metadata:type_name -> google.protobuf.Struct
	25, // 1: maximus.v1.SubmitDecisionResponse.created_at:type_name -> google.protobuf.Timestamp
	25, // 2: maximus.v1.ListDecisionsRequest.start_time:type_name -> google.protobuf.Timestamp
	25, // 3: maximus.v1.ListDecisionsRequest.end_time:type_name -> google.protobuf.Timestamp
	10, // 4: maximus.v1.ListDecisionsResponse.decisions:type_name -> maximus.v1.Decision
	24, // 5: maximus.v1.Decision.metadata:type_name -> google.protobuf.Struct
	25, // 6: maximus.v1.Decision.created_at:type_name -> google.protobuf.Timestamp
	25, // 7: maximus.v1.Decision.updated_at:type_name -> google.protobuf.Timestamp
	25, // 8: maximus.v1.Decision.resolved_at:type_name -> google.protobuf.Timestamp
	0,  // 9: maximus.v1.DecisionEvent.event_type:type_name -> maximus.v1.DecisionEvent.EventType
	10, // 10: maximus.v1.DecisionEvent.decision:type_name -> maximus.v1.Decision
	25, // 11: maximus.v1.DecisionEvent.timestamp:type_name -> google.protobuf.Timestamp
	24, // 12: maximus.v1.DecisionEvent.changes:type_name -> google.protobuf.Struct
	25, // 13: maximus.v1.GetMetricsRequest.start_time:type_name -> google.protobuf.Timestamp
	25, // 14: maximus.v1.GetMetricsRequest.end_time:type_name -> google.protobuf.Timestamp
	20, // 15: maximus.v1.GovernanceMetrics.decisions_by_priority:type_name -> maximus.v1.GovernanceMetrics.DecisionsByPriorityEntry
	21, // 16: maximus.v1.GovernanceMetrics.decisions_by_type:type_name -> maximus.v1.GovernanceMetrics.DecisionsByTypeEntry
	25, // 17: maximus.v1.GovernanceMetrics.start_time:type_name -> google.protobuf.Timestamp
	25, // 18: maximus.v1.GovernanceMetrics.end_time:type_name -> google.protobuf.Timestamp
	1,  // 19: maximus.v1.HealthCheckResponse.status:type_name -> maximus.v1.HealthCheckResponse.ServingStatus
	25, // 20: maximus.v1.HealthCheckResponse.timestamp:type_name -> google.protobuf.Timestamp
	22, // 21: maximus.v1.HealthCheckResponse.components:type_name -> maximus.v1.HealthCheckResponse.ComponentsEntry
	2,  // 22: maximus.v1.BatchSubmitRequest.decisions:type_name -> maximus.v1.SubmitDecisionRequest
	23, // 23: maximus.v1.BatchSubmitResponse.results:type_name -> maximus.v1.BatchSubmitResponse.Result
	2,  // 24: maximus.v1.MaximusOrchestrator.SubmitDecision:input_type -> maximus.v1.SubmitDecisionRequest
	4,  // 25: maximus.v1.MaximusOrchestrator.GetDecision:input_type -> maximus.v1.GetDecisionRequest
	5,  // 26: maximus.v1.MaximusOrchestrator.ListDecisions:input_type -> maximus.v1.ListDecisionsRequest
	7,  // 27: maximus.v1.MaximusOrchestrator.UpdateDecisionStatus:input_type -> maximus.v1.UpdateDecisionStatusRequest
	8,  // 28: maximus.v1.MaximusOrchestrator.DeleteDecision:input_type -> maximus.v1.DeleteDecisionRequest
	11, // 29: maximus.v1.MaximusOrchestrator.WatchDecision:input_type -> maximus.v1.WatchDecisionRequest
	12, // 30: maximus.v1.MaximusOrchestrator.StreamAllEvents:input_type -> maximus.v1.StreamEventsRequest
	14, // 31: maximus.v1.MaximusOrchestrator.GetGovernanceMetrics:input_type -> maximus.v1.GetMetricsRequest
	16, // 32: maximus.v1.MaximusOrchestrator.GetServiceHealth:input_type -> maximus.v1.HealthCheckRequest
	18, // 33: maximus.v1.MaximusOrchestrator.BatchSubmitDecisions:input_type -> maximus.v1.BatchSubmitRequest
	3,  // 34: maximus.v1.MaximusOrchestrator.SubmitDecision:output_type -> maximus.v1.SubmitDecisionResponse
	10, // 35: maximus.v1.MaximusOrchestrator.GetDecision:output_type -> maximus.v1.Decision
	6,  // 36: maximus.v1.MaximusOrchestrator.ListDecisions:output_type -> maximus.v1.ListDecisionsResponse
	10, // 37: maximus.v1.MaximusOrchestrator.UpdateDecisionStatus:output_type -> maximus.v1.Decision
	9,  // 38: maximus.v1.MaximusOrchestrator.DeleteDecision:output_type -> maximus.v1.DeleteDecisionResponse
	13, // 39: maximus.v1.MaximusOrchestrator.WatchDecision:output_type -> maximus.v1.DecisionEvent
	13, // 40: maximus.v1.MaximusOrchestrator.StreamAllEvents:output_type -> maximus.v1.DecisionEvent
	15, // 41: maximus.v1.MaximusOrchestrator.GetGovernanceMetrics:output_type -> maximus.v1.GovernanceMetrics
	17, // 42: maximus.v1.MaximusOrchestrator.GetServiceHealth:output_type -> maximus.v1.HealthCheckResponse
	19, // 43: maximus.v1.MaximusOrchestrator.BatchSubmitDecisions:output_type -> maximus.v1.BatchSubmitResponse
	34, // [34:44] is the sub-list for method output_type
	24, // [24:34] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_maximus_maximus_proto_init() }
func file_maximus_maximus_proto_init() {
	if File_maximus_maximus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_maximus_maximus_proto_rawDesc), len(file_maximus_maximus_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_maximus_maximus_proto_goTypes,
		DependencyIndexes: file_maximus_maximus_proto_depIdxs,
		EnumInfos:         file_maximus_maximus_proto_enumTypes,
		MessageInfos:      file_maximus_maximus_proto_msgTypes,
	}.Build()
	File_maximus_maximus_proto = out.File
	file_maximus_maximus_proto_goTypes = nil
	file_maximus_maximus_proto_depIdxs = nil
}
