# MAXIMUS AI 3.0 - All-in-One Kubernetes Manifests
# ⚠️ For production, split into separate files

---
apiVersion: v1
kind: Namespace
metadata:
  name: maximus-ai
  labels:
    name: maximus-ai

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: maximus-config
  namespace: maximus-ai
data:
  log_level: "INFO"
  environment: "production"
  redis_url: "redis://redis:6379"
  enable_predictive_coding: "true"
  enable_skill_learning: "true"
  enable_neuromodulation: "true"
  enable_ethical_ai: "true"

---
apiVersion: v1
kind: Secret
metadata:
  name: maximus-secrets
  namespace: maximus-ai
type: Opaque
stringData:
  postgres_url: "postgresql://maximus:CHANGE_ME@postgres:5432/maximus_kb"
  gemini_api_key: "CHANGE_ME"
  anthropic_api_key: "CHANGE_ME"
  openai_api_key: "CHANGE_ME"

---
apiVersion: v1
kind: Service
metadata:
  name: maximus-core
  namespace: maximus-ai
  labels:
    app: maximus-core
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8150
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: metrics
    protocol: TCP
  selector:
    app: maximus-core

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maximus-models-pvc
  namespace: maximus-ai
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: maximus-ingress
  namespace: maximus-ai
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - maximus.example.com
    secretName: maximus-tls
  rules:
  - host: maximus.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: maximus-core
            port:
              number: 8150

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: maximus-hpa
  namespace: maximus-ai
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: maximus-core
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: maximus-pdb
  namespace: maximus-ai
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: maximus-core
