# Docker Compose - Mock Vulnerable Applications
# Purpose: Intentionally vulnerable apps for Adaptive Immunity wargaming validation
# WARNING: DO NOT EXPOSE TO INTERNET - LOCAL TESTING ONLY

version: '3.8'

services:
  mock-sql-injection:
    build:
      context: ./backend/services/mock_vulnerable_apps
      dockerfile: Dockerfile.sql
    container_name: maximus-mock-sqli
    ports:
      - "9081:9081"
    networks:
      - immune_test
    restart: unless-stopped
    labels:
      - "maximus.role=mock-vulnerable"
      - "maximus.vulnerability=sql-injection"

  mock-xss:
    build:
      context: ./backend/services/mock_vulnerable_apps
      dockerfile: Dockerfile.xss
    container_name: maximus-mock-xss
    ports:
      - "9082:9082"
    networks:
      - immune_test
    restart: unless-stopped
    labels:
      - "maximus.role=mock-vulnerable"
      - "maximus.vulnerability=xss"

  mock-cmd-injection:
    build:
      context: ./backend/services/mock_vulnerable_apps
      dockerfile: Dockerfile.cmd
    container_name: maximus-mock-cmdi
    ports:
      - "9083:9083"
    networks:
      - immune_test
    restart: unless-stopped
    labels:
      - "maximus.role=mock-vulnerable"
      - "maximus.vulnerability=command-injection"

  mock-path-traversal:
    build:
      context: ./backend/services/mock_vulnerable_apps
      dockerfile: Dockerfile.path
    container_name: maximus-mock-path
    ports:
      - "9084:9084"
    networks:
      - immune_test
    restart: unless-stopped
    labels:
      - "maximus.role=mock-vulnerable"
      - "maximus.vulnerability=path-traversal"

  mock-ssrf:
    build:
      context: ./backend/services/mock_vulnerable_apps
      dockerfile: Dockerfile.ssrf
    container_name: maximus-mock-ssrf
    ports:
      - "9085:9085"
    networks:
      - immune_test
    restart: unless-stopped
    labels:
      - "maximus.role=mock-vulnerable"
      - "maximus.vulnerability=ssrf"

networks:
  immune_test:
    external: true
    name: maximus_immune_test
