# Service Registry Sidecars - All Running Services
# Integra TODOS os serviços atualmente em execução:
#   Layer 2 (Sistema Imune): active-immune-core
#   Layer 3 (Sensorial): osint, nmap, ip-intel
#   Layer 4 (Utilitários): vault, hitl-patch, wargaming-crisol
#
# Usage: docker compose -f docker-compose.all-services-sidecars.yml up -d

version: '3.8'

networks:
  maximus-network:
    external: true
  maximus-ai-network:
    external: true

services:
  # ====================================================================
  # LAYER 2 - SISTEMA IMUNE
  # ====================================================================

  active-immune-core-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: active-immune-core-sidecar
    environment:
      - SERVICE_NAME=active_immune_core_service
      - SERVICE_HOST=active-immune-core
      - SERVICE_PORT=8200
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network
      - maximus-ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  # ====================================================================
  # LAYER 3 - SENSORIAL
  # ====================================================================

  osint-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: osint-sidecar
    environment:
      - SERVICE_NAME=osint_service
      - SERVICE_HOST=vertice-osint
      - SERVICE_PORT=8049
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network
      - maximus-ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  nmap-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: nmap-sidecar
    environment:
      - SERVICE_NAME=nmap_service
      - SERVICE_HOST=vertice-nmap
      - SERVICE_PORT=8047
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network
      - maximus-ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  ip-intel-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: ip-intel-sidecar
    environment:
      - SERVICE_NAME=ip_intel_service
      - SERVICE_HOST=vertice-ip-intel
      - SERVICE_PORT=8034
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network
      - maximus-ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  # ====================================================================
  # LAYER 4 - UTILITÁRIOS
  # ====================================================================

  vault-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: vault-sidecar
    environment:
      - SERVICE_NAME=vault_service
      - SERVICE_HOST=vertice-vault
      - SERVICE_PORT=8200
      - SERVICE_HEALTH_ENDPOINT=/v1/sys/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network
      - maximus-ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  hitl-patch-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: hitl-patch-sidecar
    environment:
      - SERVICE_NAME=hitl_patch_service
      - SERVICE_HOST=vertice-hitl-patch
      - SERVICE_PORT=8888
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network
      - maximus-ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  wargaming-crisol-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: wargaming-crisol-sidecar
    environment:
      - SERVICE_NAME=wargaming_crisol_service
      - SERVICE_HOST=vertice-wargaming-crisol
      - SERVICE_PORT=8888
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network
      - maximus-ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
