version: '3.8'

services:
  active_immune_core:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vertice-active-immune-core
    hostname: vertice-active-immune-core
    ports:
      - "8820:8000"
    environment:
      - SERVICE_NAME=active_immune_core
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=8000
      - LOG_LEVEL=INFO
      - ENVIRONMENT=development
      - REDIS_URL=redis://vertice-redis:6379
      - POSTGRES_URL=postgresql://postgres:postgres@vertice-postgres:5432/vertice
    networks:
      - maximus-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - vertice-redis
      - vertice-postgres

  active_immune_core-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: vertice-active-immune-core-sidecar
    environment:
      - SERVICE_NAME=active_immune_core
      - SERVICE_HOST=vertice-active-immune-core
      - SERVICE_PORT=8000
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    depends_on:
      active_immune_core:
        condition: service_started
    networks:
      - maximus-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

networks:
  maximus-network:
    external: true
