# ═══════════════════════════════════════════════════════════════════════════
# GITHUB SPONSORS CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════
#
# Support Vértice-MAXIMUS development through GitHub Sponsors
#
# ═══════════════════════════════════════════════════════════════════════════

# GitHub Sponsors
github: [JuanCS-Dev]

# Other platforms (optional - uncomment and configure as needed)
# patreon: JuanCS-Dev
# open_collective: vertice-maximus
# ko_fi: JuanCS-Dev
# tidelift: npm/vertice-maximus
# custom: ["https://vertice-maximus.web.app/sponsor"]
