# Docker Compose - Redis High Availability with Sentinel
# VÉRTICE Platform - FASE 2
#
# Architecture:
#   - 1 Master + 2 Replicas (automatic failover)
#   - 3 Sentinels (quorum=2 for leader election)
#
# Usage:
#   docker compose -f docker-compose.redis-ha.yml up -d
#
# Failover Test:
#   docker compose -f docker-compose.redis-ha.yml stop redis-master
#   docker compose -f docker-compose.redis-ha.yml exec redis-sentinel-1 redis-cli -p 26379 SENTINEL get-master-addr-by-name mymaster

version: '3.8'

networks:
  redis-ha-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
  maximus-network:
    external: true

volumes:
  redis-master-data:
  redis-replica-1-data:
  redis-replica-2-data:

services:
  # ===================================
  # Redis Master
  # ===================================
  redis-master:
    image: redis:7.2-alpine
    container_name: vertice-redis-master
    hostname: redis-master
    command: >
      redis-server
      --appendonly yes
      --appendfilename "appendonly.aof"
      --save 900 1
      --save 300 10
      --save 60 10000
    ports:
      - "6379:6379"
    volumes:
      - redis-master-data:/data
    networks:
      redis-ha-network:
        aliases:
          - redis-master
        ipv4_address: 172.30.0.10
      maximus-network:
        aliases:
          - redis-master
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  # ===================================
  # Redis Replica 1
  # ===================================
  redis-replica-1:
    image: redis:7.2-alpine
    container_name: vertice-redis-replica-1
    command: >
      redis-server
      --replicaof redis-master 6379
      --appendonly yes
      --appendfilename "appendonly.aof"
    ports:
      - "6380:6379"
    volumes:
      - redis-replica-1-data:/data
    networks:
      - redis-ha-network
      - maximus-network
    depends_on:
      redis-master:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  # ===================================
  # Redis Replica 2
  # ===================================
  redis-replica-2:
    image: redis:7.2-alpine
    container_name: vertice-redis-replica-2
    command: >
      redis-server
      --replicaof redis-master 6379
      --appendonly yes
      --appendfilename "appendonly.aof"
    ports:
      - "6381:6379"
    volumes:
      - redis-replica-2-data:/data
    networks:
      - redis-ha-network
      - maximus-network
    depends_on:
      redis-master:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  # ===================================
  # Sentinel 1
  # ===================================
  redis-sentinel-1:
    image: redis:7.2-alpine
    container_name: vertice-redis-sentinel-1
    entrypoint: ["/sentinel-entrypoint.sh"]
    ports:
      - "26379:26379"
    volumes:
      - ./redis-sentinel.conf:/etc/redis/sentinel.conf
      - ./sentinel-entrypoint.sh:/sentinel-entrypoint.sh
    networks:
      - redis-ha-network
      - maximus-network
    depends_on:
      redis-master:
        condition: service_healthy
    restart: unless-stopped

  # ===================================
  # Sentinel 2
  # ===================================
  redis-sentinel-2:
    image: redis:7.2-alpine
    container_name: vertice-redis-sentinel-2
    entrypoint: ["/sentinel-entrypoint.sh"]
    ports:
      - "26380:26379"
    volumes:
      - ./redis-sentinel.conf:/etc/redis/sentinel.conf
      - ./sentinel-entrypoint.sh:/sentinel-entrypoint.sh
    networks:
      - redis-ha-network
      - maximus-network
    depends_on:
      redis-master:
        condition: service_healthy
    restart: unless-stopped

  # ===================================
  # Sentinel 3
  # ===================================
  redis-sentinel-3:
    image: redis:7.2-alpine
    container_name: vertice-redis-sentinel-3
    entrypoint: ["/sentinel-entrypoint.sh"]
    ports:
      - "26381:26379"
    volumes:
      - ./redis-sentinel.conf:/etc/redis/sentinel.conf
      - ./sentinel-entrypoint.sh:/sentinel-entrypoint.sh
    networks:
      - redis-ha-network
      - maximus-network
    depends_on:
      redis-master:
        condition: service_healthy
    restart: unless-stopped
