# Support Services Sidecars - Infrastructure & Utilities
# Integrates: atlas, network-monitor
#
# Usage: docker compose -f docker-compose.support-sidecars.yml up -d

version: '3.8'

networks:
  maximus-network:
    external: true
  maximus-ai-network:
    external: true

services:
  # ====================================================================
  # ATLAS SERVICE SIDECAR
  # ====================================================================
  atlas-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: atlas-sidecar
    environment:
      - SERVICE_NAME=atlas_service
      - SERVICE_HOST=vertice-atlas
      - SERVICE_PORT=8109
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network
      - maximus-ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  # ====================================================================
  # NETWORK MONITOR SERVICE SIDECAR
  # ====================================================================
  network-monitor-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: network-monitor-sidecar
    environment:
      - SERVICE_NAME=network_monitor_service
      - SERVICE_HOST=maximus-network-monitor
      - SERVICE_PORT=8044
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network
      - maximus-ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
