# Offensive Services Sidecars - Pentesting & Attack Simulation
# Integrates: social-eng, malware-analysis
#
# Usage: docker compose -f docker-compose.offensive-sidecars.yml up -d

version: '3.8'

networks:
  maximus-network:
    external: true
  maximus-ai-network:
    external: true

services:
  # ====================================================================
  # SOCIAL ENGINEERING SERVICE SIDECAR
  # ====================================================================
  social-eng-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: social-eng-sidecar
    environment:
      - SERVICE_NAME=social_eng_service
      - SERVICE_HOST=vertice-social-eng
      - SERVICE_PORT=8112
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network
      - maximus-ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  # ====================================================================
  # MALWARE ANALYSIS SERVICE SIDECAR
  # ====================================================================
  malware-analysis-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: malware-analysis-sidecar
    environment:
      - SERVICE_NAME=malware_analysis_service
      - SERVICE_HOST=vertice-malware-analysis
      - SERVICE_PORT=8114
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network
      - maximus-ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
