# Layer 1 (Sistema Nervoso) - Sidecars para Service Registry
# Integra os 3 serviços restantes da Camada 1:
#   - maximus-orchestrator
#   - maximus-predict
#   - vertice-maximus_eureka
#
# Usage: docker compose -f docker-compose.layer1-sidecars.yml up -d

version: '3.8'

networks:
  maximus-network:
    external: true
  maximus-ai-network:
    external: true

services:
  # ====================================================================
  # SIDECAR: Maximus Orchestrator
  # ====================================================================
  maximus-orchestrator-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: maximus-orchestrator-sidecar
    environment:
      - SERVICE_NAME=maximus_orchestrator_service
      - SERVICE_HOST=maximus-orchestrator
      - SERVICE_PORT=8016
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network           # Para comunicação com Service Registry
      - maximus-ai-network         # Para comunicação com maximus-orchestrator
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  # ====================================================================
  # SIDECAR: Maximus Predict
  # ====================================================================
  maximus-predict-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: maximus-predict-sidecar
    environment:
      - SERVICE_NAME=maximus_predict_service
      - SERVICE_HOST=maximus-predict
      - SERVICE_PORT=8040
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network           # Para comunicação com Service Registry
      - maximus-ai-network         # Para comunicação com maximus-predict
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  # ====================================================================
  # SIDECAR: Maximus Eureka
  # ====================================================================
  maximus-eureka-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: maximus-eureka-sidecar
    environment:
      - SERVICE_NAME=maximus_eureka_service
      - SERVICE_HOST=vertice-maximus_eureka
      - SERVICE_PORT=8200
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network           # Para comunicação com Service Registry
      - maximus-ai-network         # Para comunicação com eureka
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
