# 🚀 ALL SIDECARS MASTER - Complete Service Registry Integration
# Consolidates ALL sidecar configurations in one file
#
# Includes:
# - Layer 1: Sistema Nervoso (4 services)
# - Layer 2: Sistema Imune (1 service)
# - Layer 3: Sensorial/Intelligence (9 services)
# - Layer 4: Utilities/Support (5 services)
# - Offensive Services (2 services)
# - API Gateway (1 service)
# - Additional Services (4 services)
#
# Total: 26 sidecars (24 application services + api_gateway + test_service)
#
# Usage: docker compose -f docker-compose.ALL-SIDECARS-MASTER.yml up -d

version: '3.8'

networks:
  maximus-network:
    external: true
  maximus-ai-network:
    external: true

services:
  # ====================================================================
  # LAYER 1 - SISTEMA NERVOSO (4 services)
  # ====================================================================

  maximus-core-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: maximus-core-sidecar
    environment:
      - SERVICE_NAME=maximus_core_service
      - SERVICE_HOST=maximus-core
      - SERVICE_PORT=8150
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network
      - maximus-ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  maximus-orchestrator-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: maximus-orchestrator-sidecar
    environment:
      - SERVICE_NAME=maximus_orchestrator_service
      - SERVICE_HOST=maximus-orchestrator
      - SERVICE_PORT=8016
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network
      - maximus-ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  maximus-predict-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: maximus-predict-sidecar
    environment:
      - SERVICE_NAME=maximus_predict_service
      - SERVICE_HOST=maximus-predict
      - SERVICE_PORT=8040
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network
      - maximus-ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  maximus-eureka-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: maximus-eureka-sidecar
    environment:
      - SERVICE_NAME=maximus_eureka_service
      - SERVICE_HOST=vertice-maximus_eureka
      - SERVICE_PORT=8200
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network
      - maximus-ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  # ====================================================================
  # LAYER 2 - SISTEMA IMUNE (1 service)
  # ====================================================================

  active-immune-core-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: active-immune-core-sidecar
    environment:
      - SERVICE_NAME=active_immune_core_service
      - SERVICE_HOST=active-immune-core
      - SERVICE_PORT=8200
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network
      - maximus-ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  # ====================================================================
  # LAYER 3 - SENSORIAL / INTELLIGENCE (9 services)
  # ====================================================================

  osint-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: osint-sidecar
    environment:
      - SERVICE_NAME=osint_service
      - SERVICE_HOST=vertice-osint
      - SERVICE_PORT=8049
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network
      - maximus-ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  nmap-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: nmap-sidecar
    environment:
      - SERVICE_NAME=nmap_service
      - SERVICE_HOST=vertice-nmap
      - SERVICE_PORT=8047
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network
      - maximus-ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  ip-intel-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: ip-intel-sidecar
    environment:
      - SERVICE_NAME=ip_intel_service
      - SERVICE_HOST=vertice-ip-intel
      - SERVICE_PORT=8034
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network
      - maximus-ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  cyber-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: cyber-sidecar
    environment:
      - SERVICE_NAME=cyber_service
      - SERVICE_HOST=vertice-cyber
      - SERVICE_PORT=8103
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network
      - maximus-ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  threat-intel-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: threat-intel-sidecar
    environment:
      - SERVICE_NAME=threat_intel_service
      - SERVICE_HOST=vertice-threat-intel
      - SERVICE_PORT=8113
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network
      - maximus-ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  ssl-monitor-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: ssl-monitor-sidecar
    environment:
      - SERVICE_NAME=ssl_monitor_service
      - SERVICE_HOST=vertice-ssl-monitor
      - SERVICE_PORT=8115
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network
      - maximus-ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  vuln-scanner-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: vuln-scanner-sidecar
    environment:
      - SERVICE_NAME=vuln_scanner_service
      - SERVICE_HOST=vertice-vuln-scanner
      - SERVICE_PORT=8111
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network
      - maximus-ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  domain-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: domain-sidecar
    environment:
      - SERVICE_NAME=domain_service
      - SERVICE_HOST=vertice-domain
      - SERVICE_PORT=8014
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network
      - maximus-ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  sinesp-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: sinesp-sidecar
    environment:
      - SERVICE_NAME=sinesp_service
      - SERVICE_HOST=vertice-sinesp
      - SERVICE_PORT=8102
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network
      - maximus-ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  # ====================================================================
  # LAYER 4 - UTILITIES / SUPPORT (5 services)
  # ====================================================================

  vault-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: vault-sidecar
    environment:
      - SERVICE_NAME=vault_service
      - SERVICE_HOST=vertice-vault
      - SERVICE_PORT=8200
      - SERVICE_HEALTH_ENDPOINT=/v1/sys/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network
      - maximus-ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  hitl-patch-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: hitl-patch-sidecar
    environment:
      - SERVICE_NAME=hitl_patch_service
      - SERVICE_HOST=vertice-hitl-patch
      - SERVICE_PORT=8888
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network
      - maximus-ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  wargaming-crisol-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: wargaming-crisol-sidecar
    environment:
      - SERVICE_NAME=wargaming_crisol_service
      - SERVICE_HOST=vertice-wargaming-crisol
      - SERVICE_PORT=8888
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network
      - maximus-ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  atlas-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: atlas-sidecar
    environment:
      - SERVICE_NAME=atlas_service
      - SERVICE_HOST=vertice-atlas
      - SERVICE_PORT=8109
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network
      - maximus-ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  network-monitor-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: network-monitor-sidecar
    environment:
      - SERVICE_NAME=network_monitor_service
      - SERVICE_HOST=maximus-network-monitor
      - SERVICE_PORT=8044
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network
      - maximus-ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  # ====================================================================
  # OFFENSIVE SERVICES (2 services)
  # ====================================================================

  social-eng-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: social-eng-sidecar
    environment:
      - SERVICE_NAME=social_eng_service
      - SERVICE_HOST=vertice-social-eng
      - SERVICE_PORT=8112
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network
      - maximus-ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  malware-analysis-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: malware-analysis-sidecar
    environment:
      - SERVICE_NAME=malware_analysis_service
      - SERVICE_HOST=vertice-malware-analysis
      - SERVICE_PORT=8114
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network
      - maximus-ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  # ====================================================================
  # TEST SERVICE
  # ====================================================================

  test-service-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: vertice-test-service-sidecar
    environment:
      - SERVICE_NAME=test_service
      - SERVICE_HOST=vertice-test-service
      - SERVICE_PORT=8080
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network
      - maximus-ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  # ====================================================================
  # MISSING SIDECARS - Added to complete integration
  # ====================================================================

  api-gateway-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: vertice-api-gateway-sidecar
    environment:
      - SERVICE_NAME=api_gateway
      - SERVICE_HOST=vertice-api-gateway
      - SERVICE_PORT=8000
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-ai-network
      - maximus-network  # Required to reach vertice-register-lb
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  ip-intelligence-service-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: vertice-ip-intelligence-service-sidecar
    environment:
      - SERVICE_NAME=ip_intelligence_service
      - SERVICE_HOST=vertice-ip-intelligence-service
      - SERVICE_PORT=8034
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  malware-analysis-service-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: vertice-malware-analysis-service-sidecar
    environment:
      - SERVICE_NAME=malware_analysis_service
      - SERVICE_HOST=vertice-malware-analysis-service
      - SERVICE_PORT=8035
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  maximus-eureka-service-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: vertice-maximus-eureka-service-sidecar
    environment:
      - SERVICE_NAME=maximus_eureka_service
      - SERVICE_HOST=vertice-maximus_eureka
      - SERVICE_PORT=8200
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
