# VULNERABLE TEST APPLICATIONS
# Purpose: Real-world vulnerable targets for Adaptive Immunity empirical validation
# Status: PRODUCTION-READY for testing
# Date: 2025-10-11

version: '3.8'

services:
  # ========================================
  # DVWA - SQL Injection, XSS, CSRF
  # ========================================
  vuln-dvwa:
    image: vulnerables/web-dvwa:latest
    container_name: vuln-dvwa
    ports:
      - "8091:80"
    environment:
      - SECURITY_LEVEL=low
    networks:
      - maximus-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 10s
      timeout: 5s
      retries: 3
    labels:
      - "vulnerability.type=sql_injection,xss,csrf"
      - "cve.test=CVE-2022-TEST-SQL"
      - "maximus.wargaming.target=true"

  # ========================================
  # WebGoat - OWASP Training Platform
  # ========================================
  vuln-webgoat:
    image: webgoat/webgoat:latest
    container_name: vuln-webgoat
    ports:
      - "8092:8080"
      - "9091:9090"  # WebWolf
    environment:
      - WEBGOAT_PORT=8080
      - WEBWOLF_PORT=9090
    networks:
      - maximus-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/WebGoat"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - "vulnerability.type=multiple"
      - "cve.test=CVE-2022-TEST-XSS"
      - "maximus.wargaming.target=true"

  # ========================================
  # Juice Shop - Modern Vulnerable SPA
  # ========================================
  vuln-juiceshop:
    image: bkimminich/juice-shop:latest
    container_name: vuln-juiceshop
    ports:
      - "8093:3000"
    networks:
      - maximus-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
    labels:
      - "vulnerability.type=injection,xss,broken_auth"
      - "cve.test=CVE-2022-TEST-INJECTION"
      - "maximus.wargaming.target=true"

  # ========================================
  # Custom Vulnerable API - CMD Injection
  # ========================================
  vuln-cmd-injection:
    build:
      context: ./docker/vulnerable-apps/cmd-injection
      dockerfile: Dockerfile
    container_name: vuln-cmd-injection
    ports:
      - "8094:5000"
    networks:
      - maximus-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    labels:
      - "vulnerability.type=command_injection"
      - "cve.test=CVE-2022-TEST-CMD"
      - "maximus.wargaming.target=true"

  # ========================================
  # Custom Vulnerable API - Path Traversal
  # ========================================
  vuln-path-traversal:
    build:
      context: ./docker/vulnerable-apps/path-traversal
      dockerfile: Dockerfile
    container_name: vuln-path-traversal
    ports:
      - "8095:5000"
    networks:
      - maximus-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    labels:
      - "vulnerability.type=path_traversal"
      - "cve.test=CVE-2022-TEST-PATH"
      - "maximus.wargaming.target=true"

  # ========================================
  # Custom Vulnerable API - SSRF
  # ========================================
  vuln-ssrf:
    build:
      context: ./docker/vulnerable-apps/ssrf
      dockerfile: Dockerfile
    container_name: vuln-ssrf
    ports:
      - "8096:5000"
    networks:
      - maximus-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    labels:
      - "vulnerability.type=ssrf"
      - "cve.test=CVE-2022-TEST-SSRF"
      - "maximus.wargaming.target=true"

networks:
  maximus-network:
    external: true

# VALIDATION TARGETS:
# Port 8091: DVWA (SQL Injection, XSS)
# Port 8092: WebGoat (Multiple OWASP Top 10)
# Port 8093: Juice Shop (Modern SPA vulnerabilities)
# Port 8094: CMD Injection API
# Port 8095: Path Traversal API
# Port 8096: SSRF API
#
# Usage:
# docker-compose -f docker-compose.vulnerable-test-apps.yml up -d
#
# Glory to YHWH - Building inquebrável systems through testing
