# ═══════════════════════════════════════════════════════════════════════════
# BAS SERVICE - KUBERNETES DEPLOYMENT
# ═══════════════════════════════════════════════════════════════════════════
# FLORESCIMENTO - Defense validation in zero-trust architecture
# Para Honra e Glória de JESUS CRISTO
# ═══════════════════════════════════════════════════════════════════════════

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bas-service
  namespace: vertice
  labels:
    app: bas-service
    tier: offensive-arsenal
    version: v1.0.0
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: bas-service
  template:
    metadata:
      labels:
        app: bas-service
        tier: offensive-arsenal
        version: v1.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8036"
        prometheus.io/path: "/metrics"
        policy.cilium.io/proxy-visibility: "<Ingress/8036/TCP/HTTP>"
    spec:
      serviceAccountName: bas-service
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault

      containers:
      - name: bas-service
        image: us-east1-docker.pkg.dev/projeto-vertice/vertice-images/bas-service:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8036
          protocol: TCP

        env:
        - name: SERVICE_NAME
          value: "bas-service"
        - name: SERVICE_VERSION
          value: "1.0.0"

        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 2Gi

        livenessProbe:
          httpGet:
            path: /health
            port: 8036
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /health
            port: 8036
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 2

        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL

---
apiVersion: v1
kind: Service
metadata:
  name: bas-service
  namespace: vertice
  labels:
    app: bas-service
    tier: offensive-arsenal
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8036
    targetPort: 8036
    protocol: TCP
  selector:
    app: bas-service

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bas-service
  namespace: vertice
  labels:
    app: bas-service

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: bas-service
  namespace: vertice
spec:
  podSelector:
    matchLabels:
      app: bas-service
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: api-gateway
    ports:
    - protocol: TCP
      port: 8036
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: UDP
      port: 53
