# ═══════════════════════════════════════════════════════════════════════════
# HITL Patch Service - Monitoring Configuration
# ═══════════════════════════════════════════════════════════════════════════
#
# Prometheus ServiceMonitor and alerting rules
#
# Author: MAXIMUS Team - Sprint 4.1
# ═══════════════════════════════════════════════════════════════════════════

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hitl-patch-service-monitor
  namespace: maximus-immunity
  labels:
    app: hitl-patch-service
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: hitl-patch-service
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    scheme: http
    
---
# ═══════════════════════════════════════════════════════════════════════════
# PrometheusRule - Alerting Rules
# ═══════════════════════════════════════════════════════════════════════════

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: hitl-patch-service-alerts
  namespace: maximus-immunity
  labels:
    app: hitl-patch-service
    prometheus: kube-prometheus
spec:
  groups:
  - name: hitl_service_alerts
    interval: 30s
    rules:
    
    # Service availability
    - alert: HITLServiceDown
      expr: up{job="hitl-patch-service"} == 0
      for: 2m
      labels:
        severity: critical
        component: hitl-service
      annotations:
        summary: "HITL Patch Service is down"
        description: "HITL service has been unavailable for more than 2 minutes"
        runbook_url: "https://docs.maximus.ai/runbooks/hitl-service-down"
    
    # High pending patches
    - alert: HITLHighPendingPatches
      expr: hitl_pending_patches > 10
      for: 1h
      labels:
        severity: warning
        component: hitl-service
      annotations:
        summary: "High number of pending patches"
        description: "More than 10 patches have been pending for over 1 hour (current: {{ $value }})"
        runbook_url: "https://docs.maximus.ai/runbooks/hitl-high-pending"
    
    # Decision lag
    - alert: HITLDecisionLag
      expr: histogram_quantile(0.95, rate(hitl_decision_duration_seconds_bucket[5m])) > 300
      for: 15m
      labels:
        severity: warning
        component: hitl-service
      annotations:
        summary: "HITL decision time is too high"
        description: "95th percentile decision time is above 5 minutes (current: {{ $value }}s)"
        runbook_url: "https://docs.maximus.ai/runbooks/hitl-decision-lag"
    
    # Low auto-approval rate
    - alert: HITLLowAutoApprovalRate
      expr: hitl_auto_approval_rate < 0.5
      for: 1h
      labels:
        severity: info
        component: hitl-service
      annotations:
        summary: "Auto-approval rate is low"
        description: "Auto-approval rate has been below 50% for 1 hour (current: {{ $value }})"
        runbook_url: "https://docs.maximus.ai/runbooks/hitl-low-auto-approval"
    
    # ML accuracy drop
    - alert: HITLMLAccuracyDrop
      expr: hitl_ml_accuracy < 0.70
      for: 30m
      labels:
        severity: warning
        component: hitl-service
      annotations:
        summary: "ML prediction accuracy has dropped"
        description: "ML accuracy is below 70% (current: {{ $value }})"
        runbook_url: "https://docs.maximus.ai/runbooks/hitl-ml-accuracy-drop"
    
    # High error rate
    - alert: HITLHighErrorRate
      expr: rate(hitl_decisions_total{decision_type="rejected"}[5m]) > 0.5
      for: 10m
      labels:
        severity: warning
        component: hitl-service
      annotations:
        summary: "High patch rejection rate"
        description: "More than 50% of patches are being rejected"
        runbook_url: "https://docs.maximus.ai/runbooks/hitl-high-error-rate"
    
    # Database connection issues
    - alert: HITLDatabaseConnectionFailed
      expr: up{job="hitl-patch-service"} == 1 and hitl_pending_patches == 0 and hitl_decisions_total == 0
      for: 5m
      labels:
        severity: critical
        component: hitl-service
      annotations:
        summary: "HITL service cannot connect to database"
        description: "Service is up but showing no metrics - likely database connection issue"
        runbook_url: "https://docs.maximus.ai/runbooks/hitl-db-connection-failed"

---
# ═══════════════════════════════════════════════════════════════════════════
# Grafana Dashboard ConfigMap
# ═══════════════════════════════════════════════════════════════════════════

apiVersion: v1
kind: ConfigMap
metadata:
  name: hitl-grafana-dashboard
  namespace: maximus-immunity
  labels:
    app: hitl-patch-service
    grafana_dashboard: "1"
data:
  hitl-dashboard.json: |
    {
      "dashboard": {
        "title": "HITL Patch Service",
        "tags": ["hitl", "adaptive-immunity", "maximus"],
        "timezone": "browser",
        "panels": [
          {
            "title": "Pending Patches",
            "targets": [{"expr": "hitl_pending_patches"}],
            "type": "graph"
          },
          {
            "title": "Decision Rate",
            "targets": [{"expr": "rate(hitl_decisions_total[5m])"}],
            "type": "graph"
          },
          {
            "title": "ML Accuracy",
            "targets": [{"expr": "hitl_ml_accuracy"}],
            "type": "gauge"
          },
          {
            "title": "Auto-Approval Rate",
            "targets": [{"expr": "hitl_auto_approval_rate"}],
            "type": "gauge"
          },
          {
            "title": "Decision Duration (p95)",
            "targets": [{"expr": "histogram_quantile(0.95, rate(hitl_decision_duration_seconds_bucket[5m]))"}],
            "type": "graph"
          }
        ]
      }
    }
