version: '3.8'
services:
  digital_thalamus:
    build: .
    container_name: digital_thalamus_service
    ports:
    - 8012:8012
    - 9012:9012
    environment:
    - SERVICE_NAME=digital_thalamus_service
    - SERVICE_HOST=0.0.0.0
    - SERVICE_PORT=8012
    - LOG_LEVEL=INFO
    - VISUAL_MAX_IMAGE_SIZE=10485760
    - AUDITORY_MAX_AUDIO_SIZE=52428800
    - CHEMICAL_MAX_PAYLOAD_SIZE=104857600
    - RATE_LIMIT_VISUAL_MAX_REQUESTS=100
    - RATE_LIMIT_AUDITORY_MAX_REQUESTS=1000
    - RATE_LIMIT_SOMATO_MAX_REQUESTS=500
    - RATE_LIMIT_CHEMICAL_MAX_REQUESTS=50
    - RATE_LIMIT_VESTIBULAR_MAX_REQUESTS=200
    - VISUAL_FILTER_TYPE=median
    - AUDITORY_FILTER_TYPE=band_pass
    - SOMATO_FILTER_TYPE=kalman
    - CHEMICAL_FILTER_TYPE=low_pass
    - VESTIBULAR_FILTER_TYPE=kalman
    - ATTENTION_OVERLOAD_THRESHOLD=0.8
    - ATTENTION_THREAT_AMPLIFICATION_FACTOR=2.0
    - ATTENTION_BINDING_THRESHOLD=0.7
    - METRICS_ENABLED=true
    - METRICS_PORT=9012
    - VISUAL_CORTEX_URL=http://visual_cortex_service:8006
    - AUDITORY_CORTEX_URL=http://auditory_cortex_service:8007
    - SOMATOSENSORY_CORTEX_URL=http://somatosensory_cortex_service:8008
    - CHEMICAL_SENSING_URL=http://chemical_sensing_service:8009
    - VESTIBULAR_SYSTEM_URL=http://vestibular_service:8010
    - PREFRONTAL_CORTEX_URL=http://prefrontal_cortex_service:8011
    volumes:
    - ./logs:/var/log/digital_thalamus
    - ./data:/app/data
    networks:
    - maximus_network
    restart: unless-stopped
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8012/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  digital_thalamus_service-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: vertice-digital-thalamus-service-sidecar
    environment:
    - SERVICE_NAME=digital_thalamus_service
    - SERVICE_HOST=digital_thalamus_service
    - SERVICE_PORT=8012
    - SERVICE_HEALTH_ENDPOINT=/health
    - REGISTRY_URL=http://vertice-register-lb:80
    - HEARTBEAT_INTERVAL=30
    - INITIAL_WAIT_TIMEOUT=60
    networks:
    - maximus-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
networks:
  maximus_network:
    external: true
    name: maximus_network
  maximus-network:
    external: true
