# Kubernetes Secret for Active Immune Core
# Sensitive configuration (passwords, tokens, etc.)
#
# IMPORTANT: In production, use a secret management tool like:
# - HashiCorp Vault
# - AWS Secrets Manager
# - Azure Key Vault
# - Google Secret Manager
#
# Apply: kubectl apply -f k8s/02-secret.yaml -n active-immune
#
# NO MOCKS, NO PLACEHOLDERS, NO TODOS - Production-ready.

apiVersion: v1
kind: Secret
metadata:
  name: active-immune-secret
  namespace: active-immune
  labels:
    app: active-immune-core
    component: secret
type: Opaque
stringData:
  # PostgreSQL Password
  # In production: Generate strong password and store securely
  ACTIVE_IMMUNE_POSTGRES_PASSWORD: "CHANGE_ME_IN_PRODUCTION"

  # API Key (if needed for external integrations)
  ACTIVE_IMMUNE_API_KEY: ""

  # JWT Secret (if using authentication)
  JWT_SECRET: "CHANGE_ME_IN_PRODUCTION_USE_LONG_RANDOM_STRING"
