route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'vertice-default'
  routes:
    - match:
        severity: critical
      receiver: 'vertice-critical'
      continue: true
    
    - match:
        component: maximus
      receiver: 'vertice-maximus'
      continue: true
    
    - match:
        component: immune
      receiver: 'vertice-immune'
      continue: true

receivers:
  - name: 'vertice-default'
    webhook_configs:
      - url: 'http://maximus_core_service:8100/alerts/webhook'
        send_resolved: true

  - name: 'vertice-critical'
    webhook_configs:
      - url: 'http://maximus_core_service:8100/alerts/critical'
        send_resolved: true

  - name: 'vertice-maximus'
    webhook_configs:
      - url: 'http://maximus_core_service:8100/alerts/maximus'
        send_resolved: true

  - name: 'vertice-immune'
    webhook_configs:
      - url: 'http://active_immune_core:8200/alerts/webhook'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']
