# Malware Containment Playbook
# Responds to malware detection on endpoints

id: malware_containment
name: "Malware Detection & Containment"
description: |
  Comprehensive response to malware detection.
  Isolates infected host, kills malicious processes,
  collects forensics, and triggers full cascade.

trigger:
  condition: "malware_detected"
  severity: "CRITICAL"
  mitre_techniques:
    - "T1204"  # User Execution
    - "T1059"  # Command and Scripting Interpreter
    - "T1547"  # Boot or Logon Autostart

max_parallel: 0
rollback_on_failure: true  # Critical - rollback if containment fails

actions:
  # Step 1: Immediate host isolation (CRITICAL - no HOTL)
  - id: "isolate_infected_host"
    type: "isolate_host"
    hotl_required: false
    timeout_seconds: 15
    retry_attempts: 5
    parameters:
      host_ip: "{{event.target_ip}}"
      isolation_level: "full"  # Complete network isolation
      allow_management: true  # Allow admin access for remediation
    rollback_action:
      type: "restore_host_network"
      parameters:
        host_ip: "{{event.target_ip}}"

  # Step 2: Kill malicious process
  - id: "terminate_malware_process"
    type: "kill_process"
    hotl_required: false
    timeout_seconds: 10
    dependencies: ["isolate_infected_host"]
    parameters:
      host_ip: "{{event.target_ip}}"
      process_id: "{{event.payload.process_id}}"
      process_name: "{{event.payload.process_name}}"
      force: true

  # Step 3: Collect comprehensive forensics
  - id: "collect_malware_forensics"
    type: "collect_forensics"
    hotl_required: false
    timeout_seconds: 120
    dependencies: ["terminate_malware_process"]
    parameters:
      target: "{{event.target_ip}}"
      artifacts:
        - "memory_dump"
        - "file_system_snapshot"
        - "process_tree"
        - "network_connections"
        - "registry_hives"
        - "malware_sample"
      encryption: true
      retention_days: 365  # Long retention for analysis

  # Step 4: Trigger coagulation cascade (requires HOTL - high impact)
  - id: "trigger_zone_cascade"
    type: "trigger_cascade"
    hotl_required: true
    timeout_seconds: 30
    dependencies: ["isolate_infected_host"]
    parameters:
      zone: "{{event.payload.network_zone}}"
      strength: "strong"
      cascade_actions:
        - "scan_zone_for_iocs"
        - "deploy_additional_sensors"
        - "increase_logging_level"

  # Step 5: Block malware C2 infrastructure
  - id: "block_c2_domains"
    type: "block_domain"
    hotl_required: false
    timeout_seconds: 20
    dependencies: ["collect_malware_forensics"]
    parameters:
      domains: "{{event.payload.c2_domains}}"
      method: "dns_sinkhole"
      global: true

  - id: "block_c2_ips"
    type: "block_ip"
    hotl_required: false
    timeout_seconds: 20
    dependencies: ["collect_malware_forensics"]
    parameters:
      source_ips: "{{event.payload.c2_ips}}"
      duration_seconds: 86400  # 24 hours
      global: true

  # Step 6: CRITICAL alert to SOC
  - id: "alert_soc_critical"
    type: "alert_soc"
    hotl_required: false
    timeout_seconds: 5
    parameters:
      severity: "CRITICAL"
      message: |
        🔴 CRITICAL: Malware Detected & Contained
        
        Infected Host: {{event.target_ip}}
        Malware Family: {{event.payload.malware_family}}
        C2 Servers: {{event.payload.c2_ips}}
        File Hash: {{event.payload.file_hash}}
        
        IMMEDIATE ACTIONS TAKEN:
        ✅ Host isolated from network
        ✅ Malicious process terminated
        ✅ Forensics collected
        ⏳ Zone cascade pending HOTL
        ✅ C2 infrastructure blocked
        
        REQUIRES IMMEDIATE INVESTIGATION
      channels:
        - "slack_soc"
        - "pagerduty_critical"
        - "email_ciso"
      escalate_to_incident: true

metadata:
  author: "MAXIMUS Team"
  version: "1.0.0"
  created_at: "2025-10-12"
  severity_justification: |
    CRITICAL severity justified by:
    - Active malware execution
    - Potential data exfiltration
    - C2 communication established
    - Lateral movement risk
  mitre_defenses:
    - "M1049"  # Antivirus/Antimalware
    - "M1031"  # Network Intrusion Prevention
    - "M1026"  # Privileged Account Management
  biological_analogy: "Full immune cascade like cytokine storm for severe infection"
