name: Credential Dumping Prevention
description: |
  Detects and prevents credential dumping attempts using tools like:
  - Mimikatz
  - ProcDump on LSASS
  - Registry SAM/SYSTEM dumps

enabled: true

trigger:
  - event: lsass_access
  - event: credential_dump_detected
  - event: sam_registry_access

conditions:
  - process.name IN ['mimikatz.exe', 'procdump.exe', 'dumpert.exe']
  - process.command_line LIKE '%lsass%'

actions:
  - kill_process:
      process_name: credential_dumper
      pid: detected_pid
  - isolate_endpoint
  - create_incident:
      severity: critical
      title: Credential Dumping Attempt
      playbook: credential_compromise_response
  - send_alert:
      message: "CRITICAL: Credential dumping detected on {hostname}"
      channel: incident_response

tags:
  - credential_access
  - mimikatz
  - lsass
  - critical

metadata:
  author: Security Operations
  version: "1.0"
  mitre_attack:
    - T1003  # OS Credential Dumping
    - T1003.001  # LSASS Memory
    - T1003.002  # Security Account Manager
