name: 🔒 Security Vulnerability
description: Report a security vulnerability (PRIVATE - DO NOT use for sensitive issues!)
title: "[SECURITY] "
labels: ["security", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ IMPORTANT: Responsible Disclosure

        **If you've discovered a CRITICAL security vulnerability:**
        - **DO NOT** create a public issue
        - **DO** email us privately at: **security@vertice-maximus.com** or **juan@vertice-maximus.com**
        - Include "[SECURITY]" in the subject line
        - We will respond within 48 hours

        **Use this template ONLY for:**
        - Low-severity security issues
        - Security enhancement suggestions
        - Security documentation improvements
        - Non-exploitable security concerns

        See our [Security Policy](https://github.com/JuanCS-Dev/V-rtice/blob/main/SECURITY.md) for full responsible disclosure process.

  - type: dropdown
    id: severity
    attributes:
      label: Severity Assessment
      description: How severe do you consider this issue?
      options:
        - Low - Security enhancement suggestion
        - Low - Documentation/configuration issue
        - Low - Non-exploitable security concern
        - Medium - Potential issue requiring investigation
        - "⚠️ HIGH/CRITICAL - I should email security@vertice-maximus.com instead"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Security Issue Description
      description: Describe the security concern
      placeholder: |
        I noticed that...
        This could potentially...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What type of security issue is this?
      options:
        - Configuration - Insecure defaults
        - Documentation - Missing security guidance
        - Dependencies - Vulnerable dependency
        - Authentication/Authorization - Access control
        - Input Validation - Injection vulnerabilities
        - Cryptography - Weak encryption
        - Secrets Management - Exposed credentials
        - Network Security - Insecure communication
        - Container Security - Docker/K8s hardening
        - Other
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of the organism is affected?
      options:
        - Frontend (Cockpit UI)
        - Backend (Services/Microservices)
        - Consciousness (MAXIMUS AI)
        - Immune System (Defensive)
        - Offensive Operations (C2, tools)
        - CLI (vertice command)
        - Infrastructure (Docker, K8s)
        - Dependencies
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could happen if this issue is exploited or not addressed?
      placeholder: |
        An attacker could...
        This might allow...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce (if applicable)
      description: How can we verify this issue?
      placeholder: |
        1. Configure Vértice with...
        2. Access endpoint...
        3. Observe...
      render: markdown

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Do you have suggestions for how to address this?
      placeholder: |
        This could be fixed by...
        Recommend implementing...

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to CVE databases, security advisories, OWASP guidelines, etc.
      placeholder: |
        - CVE-YYYY-XXXXX
        - https://owasp.org/...
        - https://cwe.mitre.org/...

  - type: input
    id: version
    attributes:
      label: Affected Version(s)
      description: Which version(s) are affected?
      placeholder: "v1.0.0, main branch, etc."
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Relevant environment information
      value: |
        - Deployment: [e.g., Docker, K8s, bare metal]
        - OS: [e.g., Ubuntu 22.04]
        - Network: [e.g., air-gapped, internet-facing]
    validations:
      required: false

  - type: checkboxes
    id: disclosure
    attributes:
      label: Responsible Disclosure Confirmation
      description: Please confirm you understand our security policy
      options:
        - label: I confirm this is a LOW severity issue appropriate for public discussion
          required: true
        - label: I have NOT disclosed this issue publicly elsewhere
          required: true
        - label: I will NOT exploit this issue maliciously
          required: true
        - label: I have read the [Security Policy](https://github.com/JuanCS-Dev/V-rtice/blob/main/SECURITY.md)
          required: true
        - label: For CRITICAL issues, I understand I should email security@vertice-maximus.com
          required: true
