apiVersion: apps/v1
kind: Deployment
metadata:
  name: vcli-go
  namespace: default
  labels:
    app: vcli-go
    version: v2.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vcli-go
  template:
    metadata:
      labels:
        app: vcli-go
        version: v2.0.0
    spec:
      containers:
      - name: vcli-go
        image: gcr.io/projeto-vertice/vcli-go:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: VCLI_ENV
          value: "production"
        - name: VCLI_VERSION
          value: "2.0.0"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - vcli
            - version
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - vcli
            - version
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: vcli-go
  namespace: default
  labels:
    app: vcli-go
spec:
  type: LoadBalancer
  selector:
    app: vcli-go
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
