# CVE Whitelist Configuration
#
# This file contains CVEs that have been reviewed and approved for whitelisting.
# All entries MUST have:
# - Valid justification explaining why CVE doesn't apply
# - Expiration date (max 1 year from approval)
# - Owner responsible for re-review
# - Approver (Tech Lead or Security Team)
#
# See DEPENDENCY_POLICY.md for full whitelist process.

version: 1.0.0

whitelisted_cves:
  # h11 - Request Smuggling Vulnerability
  - id: CVE-2025-43859
    package: h11==0.14.0
    cvss: 7.5
    severity: HIGH
    justification: |
      h11 0.14.0 has a request smuggling vulnerability via lenient line terminator parsing.

      DEPENDENCY CONFLICT: Cannot upgrade to h11>=0.16.0 due to httpcore dependency constraint.
      httpcore 1.0.8 requires h11<0.15,>=0.13 - resolution impossible without major httpx/httpcore upgrade.

      MITIGATIONS IN PLACE:
      - Auth service runs behind API gateway with request validation
      - Nginx reverse proxy performs strict HTTP parsing (rejects malformed requests)
      - Service only handles trusted internal traffic (no direct internet exposure)
      - Request/response logging active for anomaly detection
      - Rate limiting enforced at gateway level

      ATTACK SURFACE: Requires attacker to send malformed chunked-encoding requests. Our gateway validates and normalizes HTTP requests before reaching service.

      PLANNED REMEDIATION: Monitor for httpcore/httpx updates supporting h11>=0.16.0. Quarterly review to check for compatible versions.

      Reference: https://nvd.nist.gov/vuln/detail/CVE-2025-43859

    mitigations:
      - "API Gateway with HTTP validation"
      - "Nginx reverse proxy (strict parsing)"
      - "No direct internet exposure (internal traffic only)"
      - "Authenticated requests only"
      - "Request/response logging + anomaly detection"

    expires_at: 2026-04-06
    owner: security-team
    approved_by: tech-lead
    approved_at: 2025-10-06
    re_review_date: 2026-01-04
    re_review_status: pending
    re_review_justification: ""

  # ecdsa - Minerva Timing Attack Vulnerability
  - id: CVE-2024-23342
    package: ecdsa==0.19.1
    cvss: 5.9
    severity: MEDIUM
    justification: |
      ecdsa 0.19.1 is vulnerable to Minerva timing attack (side-channel attack). NO FIX AVAILABLE - fundamental Python limitation.

      ATTACK REQUIREMENTS: Requires local access to execution environment, precise timing measurements (hardware access), thousands of samples for statistical analysis. Only affects signature GENERATION (not verification).

      OUR USAGE (LOW RISK): Auth service uses ecdsa ONLY for signature VERIFICATION (read-only). We do NOT generate ECDSA signatures (we use RSA/EdDSA for signing). python-jose uses it for validating external JWT tokens only.

      DEPLOYMENT ENVIRONMENT: Containerized deployment (Docker isolation), no local access to container, ephemeral containers, cloud environment with hardware noise (timing attacks ineffective).

      Reference: https://nvd.nist.gov/vuln/detail/CVE-2024-23342

    mitigations:
      - "Signature verification only (no generation)"
      - "Container isolation (no local access)"
      - "Ephemeral containers"
      - "Cloud environment (hardware timing noise)"
      - "Alternative algorithms used for signing (RSA/EdDSA)"

    expires_at: 2026-04-06
    owner: security-team
    approved_by: tech-lead
    approved_at: 2025-10-06
    re_review_date: 2026-01-04
    re_review_status: pending
    re_review_justification: ""

  # h11 - Side-channel Attack (GHSA duplicate)
  - id: GHSA-vqfr-h8mv-ghfj
    package: h11==0.14.0
    cvss: 7.5
    severity: HIGH
    justification: |
      Duplicate entry for h11 request smuggling (same as CVE-2025-43859). Same dependency conflict with httpcore 1.0.8 requiring h11<0.15. Same mitigations apply.

    mitigations:
      - "API Gateway with HTTP validation"
      - "Nginx reverse proxy (strict parsing)"
      - "No direct internet exposure"

    expires_at: 2026-04-06
    owner: security-team
    approved_by: tech-lead
    approved_at: 2025-10-06
    re_review_date: 2026-01-04
    re_review_status: pending
    re_review_justification: ""

  # ecdsa - Python Side-Channel Limitation (GHSA duplicate)
  - id: GHSA-wj6h-64fc-37mp
    package: ecdsa==0.19.1
    cvss: 5.9
    severity: MEDIUM
    justification: |
      General advisory that ecdsa does not protect against side-channel attacks. Architectural limitation of Python (no constant-time primitives). Same as CVE-2024-23342. Same mitigations apply.

    mitigations:
      - "Signature verification only (no generation)"
      - "Container isolation"
      - "Alternative algorithms for signing"

    expires_at: 2026-04-06
    owner: security-team
    approved_by: tech-lead
    approved_at: 2025-10-06
    re_review_date: 2026-01-04
    re_review_status: pending
    re_review_justification: ""
  # Example entry (uncomment and modify when needed):
  #
  # - id: CVE-2024-12345
  #   package: example-lib==1.2.3
  #   cvss: 7.5
  #   severity: HIGH
  #   justification: |
  #     This CVE only affects Windows systems via a specific registry key exploit.
  #     Our service runs exclusively on Linux containers with no registry access.
  #
  #     Reference: https://nvd.nist.gov/vuln/detail/CVE-2024-12345
  #     Analysis: Confirmed with Security Team on 2025-01-15
  #
  #   mitigations:
  #     - "Containerized deployment (no host access)"
  #     - "Network segmentation (isolated subnet)"
  #     - "SELinux enforcing mode"
  #
  #   expires_at: 2025-12-31
  #   owner: security-team
  #   approved_by: tech-lead-name
  #   approved_at: 2025-01-15
  #
  #   re_review_date: 2025-10-01
  #   re_review_status: pending  # pending | approved | rejected
  #   re_review_justification: ""

# Validation Rules (enforced by check-cve-whitelist.sh):
# ✅ All fields are required
# ✅ expires_at must be <= 1 year from approved_at
# ✅ re_review_date must be every 90 days
# ✅ CVSS score must match official NVD database
# ✅ Package version must match exactly (no ranges)
# ✅ Justification must be >= 50 characters
