version: '3.8'
services:
  network_recon_service:
    build: .
    container_name: network_recon_service
    ports:
    - 8032:8032
    - 9032:9032
    cap_add:
    - NET_ADMIN
    - NET_RAW
    environment:
    - SERVICE_NAME=network_reconnaissance
    - SERVICE_HOST=0.0.0.0
    - SERVICE_PORT=8032
    - LOG_LEVEL=INFO
    - DEFAULT_MASSCAN_RATE=10000
    - DEFAULT_NMAP_TIMING=3
    - MAX_SCAN_RATE=100000
    - DEFAULT_DEEP_SCAN_THRESHOLD=100
    - ENABLE_ASA_INTEGRATION=true
    - VISUAL_CORTEX_URL=http://visual_cortex_service:8006
    - AUDITORY_CORTEX_URL=http://auditory_cortex_service:8007
    - SOMATOSENSORY_URL=http://somatosensory_service:8008
    - CHEMICAL_SENSING_URL=http://chemical_sensing_service:8009
    - VESTIBULAR_URL=http://vestibular_service:8010
    - PREFRONTAL_CORTEX_URL=http://prefrontal_cortex_service:8011
    - DIGITAL_THALAMUS_URL=http://digital_thalamus_service:8012
    - NARRATIVE_FILTER_URL=http://narrative_manipulation_filter:8013
    - AI_IMMUNE_SYSTEM_URL=http://ai_immune_system:8014
    - HOMEOSTATIC_REGULATION_URL=http://homeostatic_regulation:8015
    - ASA_REQUEST_TIMEOUT=10.0
    - SCAN_TIMEOUT=3600
    - METRICS_ENABLED=true
    - METRICS_PORT=9032
    volumes:
    - ./logs:/var/log/network_recon
    - ./data:/app/data
    networks:
    - maximus_network
    restart: unless-stopped
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8032/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
    - visual_cortex_service
    - digital_thalamus_service
    - homeostatic_regulation
  network_recon_service-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: vertice-network-recon-service-sidecar
    environment:
    - SERVICE_NAME=network_recon_service
    - SERVICE_HOST=network_recon_service
    - SERVICE_PORT=8032
    - SERVICE_HEALTH_ENDPOINT=/health
    - REGISTRY_URL=http://vertice-register-lb:80
    - HEARTBEAT_INTERVAL=30
    - INITIAL_WAIT_TIMEOUT=60
    networks:
    - maximus-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
networks:
  maximus_network:
    external: true
    name: maximus_network
  maximus-network:
    external: true
