---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvp
  namespace: vertice-subordinates
  labels:
    app: mvp
    service: vision-protocol
    tier: subordinate
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: mvp
  template:
    metadata:
      labels:
        app: mvp
        service: vision-protocol
        tier: subordinate
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9093"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: mvp
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: mvp
          image: ghcr.io/vertice/mvp:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8153
              name: http
              protocol: TCP
            - containerPort: 9093
              name: metrics
              protocol: TCP
          env:
            # Common config
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: subordinates-config
                  key: ENVIRONMENT
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: subordinates-config
                  key: LOG_LEVEL
            - name: MVP_PORT
              valueFrom:
                configMapKeyRef:
                  name: subordinates-config
                  key: MVP_PORT

            # Secrets
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: subordinates-secrets
                  key: ANTHROPIC_API_KEY
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: subordinates-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: subordinates-secrets
                  key: POSTGRES_PASSWORD

            # Database
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: subordinates-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: subordinates-config
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: subordinates-config
                  key: POSTGRES_DB

            # Redis
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: subordinates-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: subordinates-config
                  key: REDIS_PORT

            # Prometheus
            - name: PROMETHEUS_URL
              valueFrom:
                configMapKeyRef:
                  name: subordinates-config
                  key: PROMETHEUS_URL

            # Narrative Configuration
            - name: NARRATIVE_TARGET_DURATION
              valueFrom:
                configMapKeyRef:
                  name: subordinates-config
                  key: NARRATIVE_TARGET_DURATION
            - name: MIN_NQS_SCORE
              valueFrom:
                configMapKeyRef:
                  name: subordinates-config
                  key: MIN_NQS_SCORE
            - name: ENABLE_LGPD_COMPLIANCE
              valueFrom:
                configMapKeyRef:
                  name: subordinates-config
                  key: ENABLE_LGPD_COMPLIANCE

          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 1Gi

          livenessProbe:
            httpGet:
              path: /health
              port: 8153
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health
              port: 8153
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 2

          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: cache
              mountPath: /app/.cache

      volumes:
        - name: tmp
          emptyDir: {}
        - name: cache
          emptyDir: {}

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - mvp
                topologyKey: kubernetes.io/hostname

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mvp
  namespace: vertice-subordinates
  labels:
    app: mvp

---
apiVersion: v1
kind: Service
metadata:
  name: mvp
  namespace: vertice-subordinates
  labels:
    app: mvp
    service: vision-protocol
spec:
  type: ClusterIP
  selector:
    app: mvp
  ports:
    - port: 8153
      targetPort: 8153
      protocol: TCP
      name: http
    - port: 9093
      targetPort: 9093
      protocol: TCP
      name: metrics

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mvp-hpa
  namespace: vertice-subordinates
  labels:
    app: mvp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mvp
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 120
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mvp-pdb
  namespace: vertice-subordinates
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: mvp

# 🤖 Generated with [Claude Code](https://claude.com/claude-code)
#
# Co-Authored-By: Claude <noreply@anthropic.com>
