global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'vertice-maximus'
    environment: 'production'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'
          category: 'monitoring'

  - job_name: 'vertice-core'
    static_configs:
      - targets: ['api_gateway:8000']
        labels:
          service: 'api_gateway'
          category: 'core'
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'vertice-maximus'
    static_configs:
      - targets:
          - 'maximus_core_service:8100'
          - 'maximus_oraculo:8101'
          - 'maximus_oraculo_v2:8102'
          - 'maximus_eureka:8103'
          - 'maximus_integration_service:8104'
          - 'maximus_orchestrator_service:8105'
          - 'maximus_predict:8106'
        labels:
          category: 'maximus'
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'vertice-immune'
    static_configs:
      - targets:
          - 'active_immune_core:8200'
          - 'adaptive_immune_system:8201'
          - 'adaptive_immunity_db:8202'
          - 'adaptive_immunity_service:8203'
          - 'ai_immune_system:8204'
          - 'immunis_api_service:8205'
          - 'immunis_bcell_service:8206'
          - 'immunis_cytotoxic_t_service:8207'
          - 'immunis_dendritic_service:8208'
          - 'immunis_helper_t_service:8209'
          - 'immunis_macrophage_service:8210'
          - 'immunis_neutrophil_service:8211'
          - 'immunis_nk_cell_service:8212'
          - 'immunis_treg_service:8213'
        labels:
          category: 'immune'
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'vertice-intelligence'
    static_configs:
      - targets:
          - 'osint_service:8300'
          - 'threat_intel_service:8301'
          - 'google_osint_service:8302'
          - 'network_recon_service:8303'
          - 'domain_service:8304'
          - 'ip_intelligence_service:8305'
          - 'vuln_intel_service:8306'
          - 'cyber_service:8307'
          - 'network_monitor_service:8308'
          - 'ssl_monitor_service:8309'
          - 'nmap_service:8310'
        labels:
          category: 'intelligence'
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'vertice-offensive'
    static_configs:
      - targets:
          - 'offensive_orchestrator_service:8400'
          - 'offensive_gateway:8401'
          - 'offensive_tools_service:8402'
          - 'web_attack_service:8403'
          - 'malware_analysis_service:8404'
          - 'c2_orchestration_service:8405'
          - 'social_eng_service:8406'
          - 'vuln_scanner_service:8407'
        labels:
          category: 'offensive'
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'vertice-defensive'
    static_configs:
      - targets:
          - 'reactive_fabric_core:8500'
          - 'reactive_fabric_analysis:8501'
          - 'reflex_triage_engine:8502'
          - 'homeostatic_regulation:8503'
          - 'bas_service:8504'
          - 'rte_service:8505'
          - 'hsas_service:8506'
        labels:
          category: 'defensive'
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'vertice-sensory'
    static_configs:
      - targets:
          - 'auditory_cortex_service:8600'
          - 'visual_cortex_service:8601'
          - 'somatosensory_service:8602'
          - 'chemical_sensing_service:8603'
          - 'vestibular_service:8604'
          - 'tegumentar_service:8605'
        labels:
          category: 'sensory'
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'vertice-cognition'
    static_configs:
      - targets:
          - 'prefrontal_cortex_service:8700'
          - 'digital_thalamus_service:8701'
          - 'memory_consolidation_service:8702'
          - 'neuromodulation_service:8703'
        labels:
          category: 'cognition'
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'vertice-higher-order'
    static_configs:
      - targets:
          - 'hcl_analyzer_service:8800'
          - 'hcl_planner_service:8801'
          - 'hcl_executor_service:8802'
          - 'hcl_kb_service:8803'
          - 'hcl_monitor_service:8804'
          - 'strategic_planning_service:8805'
          - 'autonomous_investigation_service:8806'
          - 'narrative_analysis_service:8807'
          - 'narrative_manipulation_filter:8808'
        labels:
          category: 'higher_order'
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'vertice-support'
    static_configs:
      - targets:
          - 'auth_service:8900'
          - 'atlas_service:8901'
          - 'agent_communication:8902'
          - 'sinesp_service:8903'
          - 'hitl_patch_service:8904'
          - 'cloud_coordinator_service:8905'
          - 'edge_agent_service:8906'
          - 'hpc_service:8907'
          - 'ethical_audit_service:8908'
          - 'adr_core_service:8909'
        labels:
          category: 'support'
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'vertice-wargaming'
    static_configs:
      - targets:
          - 'wargaming_crisol:9000'
          - 'mock_vulnerable_apps:9001'
          - 'tataca_ingestion:9002'
          - 'seriema_graph:9003'
          - 'purple_team:9004'
          - 'predictive_threat_hunting_service:9005'
        labels:
          category: 'wargaming'
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgres'
          category: 'infrastructure'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'
          category: 'infrastructure'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node'
          category: 'infrastructure'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: 'cadvisor'
          category: 'infrastructure'
