# CVE Whitelist Configuration
#
# This file contains CVEs that have been reviewed and approved for whitelisting.
# All entries MUST have:
# - Valid justification explaining why CVE doesn't apply
# - Expiration date (max 1 year from approval)
# - Owner responsible for re-review
# - Approver (Tech Lead or Security Team)
#
# See DEPENDENCY_POLICY.md for full whitelist process.

version: 1.0.0

whitelisted_cves: []
  # Example entry (uncomment and modify when needed):
  #
  # - id: CVE-2024-12345
  #   package: example-lib==1.2.3
  #   cvss: 7.5
  #   severity: HIGH
  #   justification: |
  #     This CVE only affects Windows systems via a specific registry key exploit.
  #     Our service runs exclusively on Linux containers with no registry access.
  #
  #     Reference: https://nvd.nist.gov/vuln/detail/CVE-2024-12345
  #     Analysis: Confirmed with Security Team on 2025-01-15
  #
  #   mitigations:
  #     - "Containerized deployment (no host access)"
  #     - "Network segmentation (isolated subnet)"
  #     - "SELinux enforcing mode"
  #
  #   expires_at: 2025-12-31
  #   owner: security-team
  #   approved_by: tech-lead-name
  #   approved_at: 2025-01-15
  #
  #   re_review_date: 2025-10-01
  #   re_review_status: pending  # pending | approved | rejected
  #   re_review_justification: ""

# Validation Rules (enforced by check-cve-whitelist.sh):
# ✅ All fields are required
# ✅ expires_at must be <= 1 year from approved_at
# ✅ re_review_date must be every 90 days
# ✅ CVSS score must match official NVD database
# ✅ Package version must match exactly (no ranges)
# ✅ Justification must be >= 50 characters
