---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: penelope
  namespace: vertice-subordinates
  labels:
    app: penelope
    service: wisdom-healing
    tier: subordinate
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: penelope
  template:
    metadata:
      labels:
        app: penelope
        service: wisdom-healing
        tier: subordinate
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9094"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: penelope
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: penelope
          image: ghcr.io/vertice/penelope:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8154
              name: http
              protocol: TCP
            - containerPort: 9094
              name: metrics
              protocol: TCP
          env:
            # Common config from ConfigMap
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: subordinates-config
                  key: ENVIRONMENT
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: subordinates-config
                  key: LOG_LEVEL
            - name: PENELOPE_PORT
              valueFrom:
                configMapKeyRef:
                  name: subordinates-config
                  key: PENELOPE_PORT

            # Secrets
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: subordinates-secrets
                  key: ANTHROPIC_API_KEY
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: subordinates-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: subordinates-secrets
                  key: POSTGRES_PASSWORD

            # Database
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: subordinates-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: subordinates-config
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: subordinates-config
                  key: POSTGRES_DB

            # Redis
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: subordinates-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: subordinates-config
                  key: REDIS_PORT

            # 7 Biblical Articles
            - name: SOPHIA_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: subordinates-config
                  key: SOPHIA_ENABLED
            - name: PRAOTES_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: subordinates-config
                  key: PRAOTES_ENABLED
            - name: TAPEINOPHROSYNE_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: subordinates-config
                  key: TAPEINOPHROSYNE_ENABLED
            - name: STEWARDSHIP_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: subordinates-config
                  key: STEWARDSHIP_ENABLED
            - name: AGAPE_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: subordinates-config
                  key: AGAPE_ENABLED
            - name: SABBATH_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: subordinates-config
                  key: SABBATH_ENABLED
            - name: SABBATH_DAY
              valueFrom:
                configMapKeyRef:
                  name: subordinates-config
                  key: SABBATH_DAY
            - name: ALETHEIA_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: subordinates-config
                  key: ALETHEIA_ENABLED

          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 2
              memory: 2Gi

          livenessProbe:
            httpGet:
              path: /health
              port: 8154
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health
              port: 8154
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 2

          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: cache
              mountPath: /app/.cache

      volumes:
        - name: tmp
          emptyDir: {}
        - name: cache
          emptyDir: {}

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - penelope
                topologyKey: kubernetes.io/hostname

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: penelope
  namespace: vertice-subordinates
  labels:
    app: penelope

---
apiVersion: v1
kind: Service
metadata:
  name: penelope
  namespace: vertice-subordinates
  labels:
    app: penelope
    service: wisdom-healing
spec:
  type: ClusterIP
  selector:
    app: penelope
  ports:
    - port: 8154
      targetPort: 8154
      protocol: TCP
      name: http
    - port: 9094
      targetPort: 9094
      protocol: TCP
      name: metrics

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: penelope-hpa
  namespace: vertice-subordinates
  labels:
    app: penelope
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: penelope
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100
          periodSeconds: 30

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: penelope-pdb
  namespace: vertice-subordinates
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: penelope

# 🤖 Generated with [Claude Code](https://claude.com/claude-code)
#
# Co-Authored-By: Claude <noreply@anthropic.com>
