---
playbook_id: "pb_ransomware_001"
name: "Ransomware Detection Response"
description: "Automated response playbook for ransomware detections"
version: "1.0"
enabled: true

# Trigger Configuration
trigger_type: "threat_type"
trigger_conditions:
  threat_types:
    - "ransomware"
    - "malware"
  severity_threshold: "high"

# Execution Settings
auto_execute: false
require_approval: true
approval_timeout_minutes: 15

# Response Steps
steps:
  - step_id: "step_001"
    name: "Isolate Infected Host"
    action_type: "isolate_host"
    order: 1
    parallel: false
    critical: true
    timeout_seconds: 60
    retry_on_failure: true
    max_retries: 2
    parameters:
      isolation_type: "network"
      preserve_state: true
    conditions:
      - type: "severity"
        operator: ">="
        value: "high"

  - step_id: "step_002"
    name: "Kill Malicious Process"
    action_type: "kill_process"
    order: 2
    parallel: false
    critical: true
    timeout_seconds: 30
    retry_on_failure: true
    max_retries: 3
    parameters:
      force: true
      dump_memory: true

  - step_id: "step_003"
    name: "Quarantine File"
    action_type: "quarantine_file"
    order: 3
    parallel: false
    critical: true
    timeout_seconds: 45
    retry_on_failure: true
    max_retries: 2
    parameters:
      quarantine_path: "/var/quarantine/"
      keep_metadata: true

  - step_id: "step_004"
    name: "Block C2 IPs"
    action_type: "block_ip"
    order: 4
    parallel: true
    critical: false
    timeout_seconds: 30
    retry_on_failure: true
    max_retries: 2
    parameters:
      scope: "global"
      duration: "permanent"

  - step_id: "step_005"
    name: "Send Critical Alert"
    action_type: "alert"
    order: 4
    parallel: true
    critical: false
    timeout_seconds: 15
    retry_on_failure: true
    max_retries: 3
    parameters:
      severity: "critical"
      channels:
        - "email"
        - "slack"
        - "pagerduty"
      message: "Ransomware detected and contained"

  - step_id: "step_006"
    name: "Collect Evidence"
    action_type: "collect_evidence"
    order: 5
    parallel: false
    critical: false
    timeout_seconds: 120
    retry_on_failure: false
    max_retries: 1
    parameters:
      evidence_types:
        - "process_dump"
        - "network_logs"
        - "file_sample"
        - "registry_snapshot"
      compress: true

  - step_id: "step_007"
    name: "Log Incident"
    action_type: "log"
    order: 6
    parallel: false
    critical: false
    timeout_seconds: 10
    retry_on_failure: true
    max_retries: 5
    parameters:
      log_level: "critical"
      include_full_context: true

# Metadata
author: "ADR Security Team"
tags:
  - "ransomware"
  - "automated"
  - "high-priority"
  - "isolation"
created_at: "2025-01-15T00:00:00Z"
updated_at: "2025-01-15T00:00:00Z"
