# Prometheus Configuration for HITL Staging
# ═══════════════════════════════════════════════════════════════════════════

global:
  scrape_interval: 30s
  evaluation_interval: 30s
  external_labels:
    environment: 'staging'
    cluster: 'local-docker'
    project: 'maximus-hitl'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['alertmanager:9093']

# Rule files
rule_files:
  # - '/etc/prometheus/rules/*.yml'

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          component: 'prometheus'

  # HITL Backend Service
  - job_name: 'hitl-backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['hitl-backend-staging:8027']
        labels:
          component: 'hitl-service'
          service: 'backend'
    scrape_interval: 15s
    scrape_timeout: 10s

  # PostgreSQL (if exporter is added)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']
  #       labels:
  #         component: 'database'

  # Redis (if exporter is added)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']
  #       labels:
  #         component: 'cache'
