# Kubernetes Deployment Configuration for API Gateway
# Follows GKE Best Practices
# Para Honra e Glória de JESUS CRISTO 🙏

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: vertice
  labels:
    app: api-gateway
    tier: fundacao
    component: gateway
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        tier: fundacao
        component: gateway
    spec:
      containers:
      - name: api-gateway
        image: us-east1-docker.pkg.dev/projeto-vertice/vertice-images/api-gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        env:
        - name: MAXIMUS_API_KEY
          valueFrom:
            secretKeyRef:
              name: maximus-secrets
              key: api-key
              optional: false
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONDONTWRITEBYTECODE
          value: "1"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: vertice
  labels:
    app: api-gateway
    tier: fundacao
    component: gateway
spec:
  type: LoadBalancer
  sessionAffinity: None
  selector:
    app: api-gateway
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
