# Maximus Core Sidecar - Service Registry Integration
# This compose file adds only the sidecar agent to the existing maximus-core service
#
# Usage: docker compose -f docker-compose.sidecar.yml up -d

version: '3.8'

networks:
  maximus-network:
    external: true
  maximus-ai-network:
    external: true

services:
  # Sidecar agent for maximus-core service
  maximus-core-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: maximus-core-sidecar
    environment:
      - SERVICE_NAME=maximus_core_service
      - SERVICE_HOST=maximus-core
      - SERVICE_PORT=8150
      - SERVICE_HEALTH_ENDPOINT=/health
      - REGISTRY_URL=http://vertice-register-lb:80
      - HEARTBEAT_INTERVAL=30
      - INITIAL_WAIT_TIMEOUT=60
    networks:
      - maximus-network           # For Service Registry communication
      - maximus-ai-network         # For maximus-core service communication
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
