version: '3.8'
services:
  narrative_filter:
    build: .
    container_name: narrative_manipulation_filter
    ports:
    - 8013:8013
    - 9013:9013
    environment:
    - SERVICE_NAME=narrative_manipulation_filter
    - SERVICE_HOST=0.0.0.0
    - SERVICE_PORT=8013
    - LOG_LEVEL=INFO
    - INFO_THRESHOLD=0.3
    - WARNING_THRESHOLD=0.6
    - CRITICAL_THRESHOLD=0.8
    - EMOTIONAL_INTENSITY_THRESHOLD=0.5
    - FALLACY_SEVERITY_THRESHOLD=0.5
    - DISTORTION_SEVERITY_THRESHOLD=0.5
    - ENABLE_BLOCKING=true
    - ENABLE_ALTERNATIVES=true
    - ENABLE_EDUCATIONAL_CONTENT=true
    - MAX_EVIDENCE_ITEMS=10
    - MAX_ALTERNATIVE_SOURCES=3
    - METRICS_ENABLED=true
    - METRICS_PORT=9013
    - PREFRONTAL_CORTEX_URL=http://prefrontal_cortex_service:8011
    - DIGITAL_THALAMUS_URL=http://digital_thalamus_service:8012
    volumes:
    - ./logs:/var/log/narrative_filter
    - ./data:/app/data
    networks:
    - maximus_network
    restart: unless-stopped
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8013/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  narrative_manipulation_filter-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: vertice-narrative-manipulation-filter-sidecar
    environment:
    - SERVICE_NAME=narrative_manipulation_filter_service
    - SERVICE_HOST=narrative_manipulation_filter
    - SERVICE_PORT=8013
    - SERVICE_HEALTH_ENDPOINT=/health
    - REGISTRY_URL=http://vertice-register-lb:80
    - HEARTBEAT_INTERVAL=30
    - INITIAL_WAIT_TIMEOUT=60
    networks:
    - maximus-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
networks:
  maximus_network:
    external: true
    name: maximus_network
  maximus-network:
    external: true
