# CVE Whitelist Configuration
#
# This file contains CVEs that have been reviewed and approved for whitelisting.
# All entries MUST have:
# - Valid justification explaining why CVE doesn't apply
# - Expiration date (max 1 year from approval)
# - Owner responsible for re-review
# - Approver (Tech Lead or Security Team)
#
# See DEPENDENCY_POLICY.md for full whitelist process.

version: 1.0.0

whitelisted_cves:
  # urllib3 - HTTP Redirect Vulnerability
  - id: CVE-2025-50181
    package: urllib3==1.26.20
    cvss: 7.5
    severity: HIGH
    justification: |
      urllib3 1.26.20 has a vulnerability where redirects can be disabled for all requests. Fix requires urllib3 ≥2.5.0.

      DEPENDENCY CONFLICT: Cannot upgrade to urllib3 ≥2.5.0 due to kubernetes dependency constraint.
      kubernetes 34.1.0 (latest stable) requires urllib3<2,>=1.26.2 - resolution impossible until kubernetes releases update.

      MITIGATIONS IN PLACE:
      - HCL executor service uses kubernetes client for controlled K8s API interactions only
      - Service runs in trusted environment (internal cluster communication)
      - Kubernetes API endpoints are known/trusted (no arbitrary HTTP requests)
      - Network policies restrict outbound connections to K8s API server only
      - TLS verification enforced for all K8s API communications

      ATTACK SURFACE: CVE affects HTTP redirect handling. Our service interacts exclusively with Kubernetes API (known endpoints, no user-controlled redirects). Risk is minimal as we don't handle arbitrary HTTP requests.

      PLANNED REMEDIATION: Monitor for kubernetes-client updates supporting urllib3 ≥2.5.0. Weekly review to check for compatible versions.

      Reference: https://nvd.nist.gov/vuln/detail/CVE-2025-50181

    mitigations:
      - "Kubernetes API client only (no arbitrary HTTP requests)"
      - "Trusted environment (internal cluster)"
      - "Known/trusted API endpoints"
      - "Network policies (K8s API server only)"
      - "TLS verification enforced"
      - "No user-controlled redirects"

    expires_at: 2026-04-06
    owner: security-team
    approved_by: tech-lead
    approved_at: 2025-10-06
    re_review_date: 2026-01-04
    re_review_status: pending
    re_review_justification: ""

  # Example entry (uncomment and modify when needed):
  #
  # - id: CVE-2024-12345
  #   package: example-lib==1.2.3
  #   cvss: 7.5
  #   severity: HIGH
  #   justification: |
  #     This CVE only affects Windows systems via a specific registry key exploit.
  #     Our service runs exclusively on Linux containers with no registry access.
  #
  #     Reference: https://nvd.nist.gov/vuln/detail/CVE-2024-12345
  #     Analysis: Confirmed with Security Team on 2025-01-15
  #
  #   mitigations:
  #     - "Containerized deployment (no host access)"
  #     - "Network segmentation (isolated subnet)"
  #     - "SELinux enforcing mode"
  #
  #   expires_at: 2025-12-31
  #   owner: security-team
  #   approved_by: tech-lead-name
  #   approved_at: 2025-01-15
  #
  #   re_review_date: 2025-10-01
  #   re_review_status: pending  # pending | approved | rejected
  #   re_review_justification: ""

# Validation Rules (enforced by check-cve-whitelist.sh):
# ✅ All fields are required
# ✅ expires_at must be <= 1 year from approved_at
# ✅ re_review_date must be every 90 days
# ✅ CVSS score must match official NVD database
# ✅ Package version must match exactly (no ranges)
# ✅ Justification must be >= 50 characters
