# ============================================================================
# PREFRONTAL CORTEX SERVICE - Logging Configuration
# Rational Control and Emotional Regulation for Maximus AI 3.0
# ============================================================================

version: 1
disable_existing_loggers: False

formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: '%(asctime)s %(name)s %(levelname)s %(message)s'

  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: /var/log/prefrontal_cortex/service.log
    maxBytes: 10485760  # 10MB
    backupCount: 10
    encoding: utf8

  json_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: /var/log/prefrontal_cortex/service.json
    maxBytes: 10485760  # 10MB
    backupCount: 10
    encoding: utf8

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: /var/log/prefrontal_cortex/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  # Prefrontal Cortex loggers
  emotional_state_monitor:
    level: DEBUG
    handlers: [console, file, json_file]
    propagate: no

  rational_decision_validator:
    level: DEBUG
    handlers: [console, file, json_file]
    propagate: no

  impulse_inhibition:
    level: DEBUG
    handlers: [console, file, json_file]
    propagate: no

  # FastAPI/Uvicorn loggers
  uvicorn:
    level: INFO
    handlers: [console, file]
    propagate: no

  uvicorn.access:
    level: INFO
    handlers: [console, file]
    propagate: no

  uvicorn.error:
    level: ERROR
    handlers: [console, error_file]
    propagate: no

  fastapi:
    level: INFO
    handlers: [console, file]
    propagate: no

root:
  level: INFO
  handlers: [console, file, json_file, error_file]
