version: '3.8'
services:
  maximus_dlq_monitor_service:
    build: .
    container_name: vertice-maximus-dlq-monitor-service
    hostname: vertice-maximus-dlq-monitor-service
    ports:
    - 8220:8220
    environment:
    - SERVICE_NAME=maximus_dlq_monitor_service
    - SERVICE_HOST=0.0.0.0
    - SERVICE_PORT=8220
    - LOG_LEVEL=INFO
    - ENVIRONMENT=development
    networks:
    - maximus-network
    restart: unless-stopped
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8220/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  maximus_dlq_monitor_service-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: vertice-maximus-dlq-monitor-service-sidecar
    environment:
    - SERVICE_NAME=maximus_dlq_monitor_service
    - SERVICE_HOST=vertice-maximus-dlq-monitor-service
    - SERVICE_PORT=8220
    - SERVICE_HEALTH_ENDPOINT=/health
    - REGISTRY_URL=http://vertice-register-lb:80
    - HEARTBEAT_INTERVAL=30
    - INITIAL_WAIT_TIMEOUT=60
    depends_on:
      maximus_dlq_monitor_service:
        condition: service_started
    networks:
    - maximus-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
networks:
  maximus-network:
    external: true
