name: Coagulation Protocol CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/coagulation/**'
      - '.github/workflows/coagulation-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/coagulation/**'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true
          cache-dependency-path: backend/coagulation/go.sum
      
      - name: Download dependencies
        working-directory: backend/coagulation
        run: go mod download
      
      - name: Build all packages
        working-directory: backend/coagulation
        run: go build -v ./...
      
      - name: Run tests
        working-directory: backend/coagulation
        run: go test -v -race -coverprofile=coverage.out ./...
      
      - name: Generate coverage report
        working-directory: backend/coagulation
        run: go tool cover -html=coverage.out -o coverage.html
      
      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: backend/coagulation/coverage.html
  
  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: backend/coagulation
          args: --timeout=5m
  
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: '-no-fail -fmt sarif -out gosec.sarif ./backend/coagulation/...'
      
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: gosec.sarif
