version: '3.8'
services:
  reflex_triage_engine:
    build: .
    container_name: vertice-reflex-triage-engine
    hostname: vertice-reflex-triage-engine
    ports:
    - 8282:8282
    environment:
    - SERVICE_NAME=reflex_triage_engine_service
    - SERVICE_HOST=0.0.0.0
    - SERVICE_PORT=8052
    - LOG_LEVEL=INFO
    - ENVIRONMENT=development
    - REDIS_URL=redis://redis:6379
    - POSTGRES_URL=postgresql://postgres:postgres@postgres:5432/db
    - MONGO_URL=mongodb://mongo:27017/db
    networks:
    - maximus-network
    restart: unless-stopped
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8052/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on: {}
  reflex_triage_engine-sidecar:
    image: vertice-registry-sidecar:latest
    container_name: vertice-reflex-triage-engine-sidecar
    environment:
    - SERVICE_NAME=reflex_triage_engine_service
    - SERVICE_HOST=vertice-reflex-triage-engine
    - SERVICE_PORT=8052
    - SERVICE_HEALTH_ENDPOINT=/health
    - REGISTRY_URL=http://vertice-register-lb:80
    - HEARTBEAT_INTERVAL=30
    - INITIAL_WAIT_TIMEOUT=60
    depends_on:
      reflex_triage_engine:
        condition: service_started
    networks:
    - maximus-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
networks:
  maximus-network:
    external: true
